### ISSUE TITLE
Explicit SSH Port Forwarding

### ISSUE THREAD

**Issue by fuzziebrain** [oracle/vagrant-boxes#1]
For the Oracle Linux Vagrantfile, SSH port forwarding isn't necessary as this is done automatically and dynamically by Vagrant. Also, Vagrant boxes for Oracle Linux have SSH password authentication turned off by default. The only way to SSH into the VM would be using the command `vagrant ssh`. It might also be worthwhile updating the README.

**Comment by gvenzl** [comment]
Thanks @fuzziebrain! @scoter-oracle, does that sound good for you, removing the ssh port forwarding?

**Comment by scoter-oracle** [comment]
Yep, I agree. I've commented it out. Thanks

**Comment by fuzziebrain** [comment]
Thanks guys! The [README](https://github.com/oracle/vagrant-boxes/blob/master/OracleLinux/README.md) might require updating too. The only way to SSH into the VM out-of-the-box is to use `vagrant ssh`.

**Comment by fuzziebrain** [comment]
Thank you again @scoter-oracle !
