### ISSUE TITLE
DG and RAC box suggestions

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#105]
Congratulations on the new DG and RAC boxes! Very nice!

I've looked though the files, and I have a few suggestions that might help avoid future problems, based on what I've seen with the other Vagrant boxes. I don't mean any of them as criticism--they're just my opinions.

**CODEOWNERS**
* I don't think the additions to the `CODEOWNERS` file will work as expected, because they contain typos.
  * "/Ora**lc**eDG/" on line 5 should be "/Ora**cl**eDG/"
  * "/Ora**lc**eRAC/" on line 6 should be "/Ora**cl**eRAC/"

**OracleDG/config/**
* I think it'd be helpful to add a `.gitignore` file in this directory that ignores `setup.env` (generated during the build), to prevent it from being accidentally committed.

**OracleDG/scripts/01_install_os_packages.sh**
* I don't think lines 27-29 are compatible with the new yum repository configuration. `public-yum-ol7.repo` is no longer included in `ol7-latest.box`, and the file is no longer being updated on yum.oracle.com.

**OracleDG/userscripts/**
* I think a .gitignore file should be added to this directory to ignore all files except `put_custom_scripts_here.txt` and `.gitignore` itself, to prevent user scripts from being accidentally committed. If you want, you can copy the `.gitignore` file from the `userscripts` directory of any of the database boxes.

**OracleDG/userscripts/put_custom_scripts_here.txt**
* I think the text on lines 6-7 should be revised. Shell scripts will be executed as root, not as the vagrant user. (This was my mistake, and I apologize. You just copied the text that I had in the file.)

**OracleDG/README.md**
* In the text describing "Running scripts after setup", I think the statement that shell scripts will be executed as the vagrant user should be revised to say that shell scripts will be executed as root. (Again, my apologies.)

**OracleRAC/config/**
* I think it'd be helpful to add a `.gitignore` file in this directory that ignores `setup.env` (generated during the build), to prevent it from being accidentally committed.

**OracleRAC/scripts/**
* I think it'd be helpful to add a `.gitignore` file in this directory that ignores `09_gi_installation.sh`, `11_gi_config.sh`, `13_RDBMS_software_installation.sh`, and `14_create_database.sh` (all generated during the build), to prevent them from being accidentally committed.

**OracleRAC/scripts/02_install_os_packages.sh**
* I don't think lines 27-29 are compatible with the new yum repository configuration. `public-yum-ol7.repo` is no longer included in `ol7-latest.box`, and the file is no longer being updated on yum.oracle.com.

**OracleRAC/userscripts/**
* I think a .gitignore file should be added to this directory to ignore all files except `put_custom_scripts_here.txt` and `.gitignore` itself, to prevent user scripts from being accidentally committed. If you want, you can copy the `.gitignore` file from the `userscripts` directory of any of the database boxes.

**OracleRAC/userscripts/put_custom_scripts_here.txt**
* I think the text on lines 6-7 should be revised. Shell scripts will be executed as root, not as the vagrant user.

**OracleRAC/README.md**
* In the text describing "Running scripts after setup", I think the statement that shell scripts will be executed as the vagrant user should be revised to say that shell scripts will be executed as root.

Again, congratulations! These boxes are a great addition.

**Comment by rcitton** [comment]
Hi Paul, really a big thank you for your review and for your hints! really appreciate!. I think I ve implemented all them. Let's see after the merge :) Thank you again Ruggero

**Comment by PaulNeumann** [comment]
@rcitton Looks great! I'll go ahead and close this issue. Thanks!
