### ISSUE TITLE
RAC box issue

### ISSUE THREAD

**Issue by XiaoYu-HN** [oracle/vagrant-boxes#106]
when i run vagrant up, it failed with many errors like below:
' ...
node2: /vagrant_scripts/01_setup_u01.sh: line 30: $'\r': command not found
...'

the cause is the .sh files in scripts directory is converted to DOS format, i use one of below method to resolve it:
1. dos2unix
2.  git config --global core.autocrlf false

**Comment by AmedeeBulle** [comment]
For the Containers Vagrant scripts i have
```
*.sh	text eol=lf
```
in the `.gitconfig` file.

Maybe we should consider having it at the top of our repo as this is a recurrent issue...

**Comment by PaulNeumann** [comment]
Yes, this was an issue for the single instance database boxes as well (#71). They now use the same `.gitattributes` file that you created for the ContainerRegistry and Kubernetes boxes.

**Comment by rcitton** [comment]
I made the changes. Thank you!

**Comment by scoter-oracle** [comment]
Issue closed with oracle#106
