### ISSUE TITLE
DB 12cR2 & 18c boxes - enable global EM Express port

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#113]
With the Oracle Database 12.2.0.1 and 18.3.0 boxes, EM Express can connect to the CDB, but not directly to the PDB. This is because only port 5500 is forwarded from the host to the guest for EM Express, and this port is used by the CDB. By default, EM Express connections to the PDB would use a different port. Being able to connect directly to the PDB using EM Express would improve usability.

Executing the procedure `DBMS_XDB_CONFIG.SETGLOBALPORTENABLED` with a parameter of `TRUE` enables EM Express to connect to both the CDB and the PDB on port 5500. This change is persistent; the procedure needs to be run only once. (The 12cR2 docs for this procedure are [here](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/arpls/DBMS_XDB_CONFIG.html#GUID-24CC7F8C-33C9-4444-A4FA-48BAD06353BA), and the 18c docs are [here](https://docs.oracle.com/en/database/oracle/oracle-database/18/arpls/DBMS_XDB_CONFIG.html#GUID-24CC7F8C-33C9-4444-A4FA-48BAD06353BA).)

Adding the following to `install.sh` after database creation would automate this:

```bash
# enable global port for EM Express
su -l oracle -c 'sqlplus / as sysdba <<EOF
   EXEC DBMS_XDB_CONFIG.SETGLOBALPORTENABLED (TRUE);
   exit
EOF'

echo 'INSTALLER: Global EM Express port enabled'
```

This suggestion is only for the 12.2.0.1 and 18.3.0 boxes. CDB/PDB doesn't apply to 11g XE, 12.1.0.2 requires a separate EM Express port for each container, and the 18c XE box already includes this functionality.

If you think this is a good idea, I'd be happy to submit a PR.

**Comment by gvenzl** [comment]
Hm, thanks for flagging this up. This should also be relevant for the docker images as well. Let me double check as I would like to fix both at once.
