### ISSUE TITLE
New version of guest additions

### ISSUE THREAD

**Issue by ethanmdavidson** [oracle/vagrant-boxes#117]
A new version of VirtualBox guest additions has been released (6.0.4 -> 6.0.6): https://www.virtualbox.org/wiki/Downloads

The [repo containing the oracle linux vagrant boxes](https://yum.oracle.com/boxes) still has 6.0.4 installed. The [vagrant-vbguest](https://github.com/dotless-de/vagrant-vbguest) plugin can be used to automatically upgrade it, but this upgrade has to be done every time you provision the base box which slows things down a little. For the best user experience, a new base box with upgraded guest additions should be created.

I understand that this repo is not for the maintenance of those boxes, but I couldn't figure out where else to bring this up. Hopefully someone here can at least point me in the right direction.

**Comment by scoter-oracle** [comment]
Updated Vagrant Boxes for both OL6 and OL7 are now available.
The same contain all the updated for the OS as well as updated VirtualBox 6.0.6 guest additions.
