### ISSUE TITLE
Invalid Certificate and HTTP 403 on download.virtualbox.org

### ISSUE THREAD

**Issue by DavisDevasia** [oracle/vagrant-boxes#121]
The SSL certificate deployed on download.virtualbox.org is NOT trusted because of host name mismatch.
Users are not able to download files even after manually trusting the certificate.
All requests to download.virtualbox.org return HTTP 403 Unauthorized Request.

**Comment by scoter-oracle** [comment]
This issue is not related to the project. BTW the same has been already fixed. Closing it.
