### ISSUE TITLE
APEX box suggestions

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#129]
Congratulations on releasing the APEX box! This is awesome!

I've looked through the files and built the box, and I have a few suggestions that might help avoid future problems, based on what I've seen with the other Vagrant boxes. I don't mean any of them as criticism--they're just my opinions.

* The `oracle-xe-18c.conf.tmpl` file must use Unix (LF) line endings, or database configuration will fail. By default, when Windows users clone the repository in Git, this file will be converted to use DOS/Windows (CR/LF) line endings, and the build will fail. To prevent this problem, I think it'd be helpful to add a `.gitattributes` file that preserves LF line feed endings for `*.tmpl` files.

* I think it'd be helpful to add a `.gitignore` file that ignores `*.rpm` files, so that users don't accidentally commit the database installer rpm.

(If you want, you can copy both the `.gitattributes` and `.gitignore` files from `/OracleDatabase/18.4.0-XE`.)

**README.md**
* In the "Connecting to Oracle" section, the SID should be "XE" and the PDB should be "XEPDB1".
* In the "Customization" section, the only items that can be customized are ORACLE_CHARACTERSET, ORACLE_PWD and SYSTEM_TIMEZONE. I suggest removing the lines for ORACLE_BASE, ORACLE_HOME, ORACLE_SID, ORACLE_PDB, and ORACLE_EDITION, to reduce potential confusion.

**Vagrantfile**
* I suggest removing the lines that install the vagrant-reload plugin, since it isn't used for this box.
* Some of the environment variables passed to `database.sh` aren't used, and can be deleted from the `Vagrantfile`. Only ORACLE_CHARACTERSET and SYSTEM_TIMEZONE are configurable. I suggest removing the lines for ORACLE_BASE, ORACLE_HOME, ORACLE_SID, ORACLE_PDB, and ORACLE_EDITION, to reduce potential confusion.

**scripts/database.sh**
* Thanks for figuring out how to use a VM host name other than "localhost" for 18c XE! Very nice!
* The `SYSTEM_TIMEZONE` environment variable is set up in the `Vagrantfile`, and it's passed to `database.sh`, but it's not used, and the VM time zone isn't being automatically set. Adding `timedatectl set-timezone "$SYSTEM_TIMEZONE"` to `database.sh` would fix this.
* I suggest adding the following code right after running `oracle-xe-18c configure` to modify permissions on tnsnames.ora and add an entry for the PDB. (This was issue #104 for the 18c XE database box.) This change would allow both the oracle and vagrant users to connect to both the CDB and the PDB using TNS:
```bash
chmod o+r /opt/oracle/product/18c/dbhomeXE/network/admin/tnsnames.ora

# add tnsnames.ora entry for PDB
echo 'XEPDB1 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = oracle-18c-apex)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = XEPDB1)
    )
  )
' >> /opt/oracle/product/18c/dbhomeXE/network/admin/tnsnames.ora
```

**scripts/install.sh**
* The ol7-latest base box already includes the new yum repository configuration, so I don't think lines 29-30 (running `ol_yum_configure.sh`) are necessary. Running this script results in the message `oracle-18c-apex: Missing /etc/yum.repos.d/public-yum-ol7.repo. Exiting` in the log.

Again, congratulations. This box will be very popular!

**Comment by scoter-oracle** [comment]
Hi Paul,

thanks for your feedback.
See what I'm going to introduce, based on your great report above:

- .gitattributes and .gitignore files added
- README.md fixed
- Vagrantfile fixed
- scripts/database.sh fixed
- scripts/install.sh _NOT_ fixed

I'm not going to remove "ol_yum_configure.sh" for now, just because we could have people still relying on an old OL7.5/7.6 box where "ol_yum_configure.sh" script hasn't been executed.
Thanks, again, for your precious feedback.

Simon

**Comment by scoter-oracle** [comment]
Pull Request #130 include everything above.

**Comment by PaulNeumann** [comment]
@scoter-oracle, Thank you for updating the box so quickly! I really appreciate your consideration.

Paul

**Comment by scoter-oracle** [comment]
You're Welcome Paul, thanks for your precious feedback; it's far easier to work in this way :)
