### ISSUE TITLE
APEX box - start ORDS on every bootup

### ISSUE THREAD

**Issue by jrsnzc** [oracle/vagrant-boxes#133]
Congratulations on releasing the APEX box!

Oracle Rest Data Services only works on the first run so I have a few suggestions:

**Vagrantfile**
- Add an inline shell provisioner script to run on every `vagrant up`.
```
# Provision and update Oracle Linux 7
...
# Provision Oracle Database on the first run
...
# Provision Oracle Application Expresss on the first run
..
# Provision Oracle Rest Data Services on the first run
...
# Start ORDS on every bootup
config.vm.provision "shell", inline: "su - oracle /home/oracle/start_ORDS.sh", run: "always" 
```
**scripts/ords.sh**
- Delete entry to prevent start twice on first run.
```
# Start ORDS
su - oracle /home/oracle/start_ORDS.sh

echo 'INSTALLER: Oracle Rest Data Services started'
```
Great initiative!

**Comment by scoter-oracle** [comment]
Thanks for your comment; you're right, we've to get ORDS started even on the possible Box reboot. That said, I'm not going to manage this by Vagrant, I'll work on Linux service creation dedicated to ORDS with the proper dependency to the Oracle XE Database Service. Stay tuned ;)
