### ISSUE TITLE
Doesn't work properly with vagrant-vbguest

### ISSUE THREAD

**Issue by ethanmdavidson** [oracle/vagrant-boxes#137]
The [vagrant-vbguest](https://github.com/dotless-de/vagrant-vbguest) plugin is used to automatically update guest additions to match the version on the host. However, it doesn't work properly with the oracle linux 7 box. I have created [an issue on vagrant-vbguest](https://github.com/dotless-de/vagrant-vbguest/issues/340) for this, and the plugin maintainer thinks that it is because the old version that is preinstalled with the box is not being uninstalled properly before the new version tries to install. 

While guest additions is available through the [ol7_developers repo](http://yum.oracle.com/repo/OracleLinux/OL7/developer/x86_64/index.html) it appears that yum was not used to install the guest additions. 

How was guest additions installed on these boxes? What is the proper way to uninstall it?

**Comment by iServe-IT** [comment]
No issues here with [vagrant-vbguest](https://github.com/dotless-de/vagrant-vbguest) on MacOS.
The plugin detects 6.0.4 and successfully updates to 6.0.8, without rebooting.

**Comment by gvenzl** [comment]
@scoter-oracle, can you take a look at this, please?

**Comment by scoter-oracle** [comment]
Guest-Additions on those boxes are installed by the official VirtualBox Guest-Add ISO.

**Comment by ethanmdavidson** [comment]
would it be possible to install the Guest-Additions from the yum repo instead? That would make it compatible with vagrant-vbguest, which means it would be easier for people to keep the guest additions up to date. With the ISO, they don't get the new guest additions version until you release a new box version.
