### ISSUE TITLE
Error with Apex user in ORDS - 503 Service Unavailable

### ISSUE THREAD

**Issue by bsk-eduardo-oliveira** [oracle/vagrant-boxes#138]
I was able to install VM with apex, oracle and ords, but when trying to access the address http: // localhost: 8080 / ords I get an error with the following message:
"503 Service Unavailable - The connection pool username or password with the name | apex || is invalid, expired, or the account is locked"
How can I fix this problem?
![img_erros_Vagrant_Apex](https://user-images.githubusercontent.com/49482276/59511562-fea06180-8e8c-11e9-84cc-24dcc01c699d.PNG)

**Comment by scoter-oracle** [comment]
Hi, we need the output of of your "vagrant up" execution to understand why it's not working. Can you please share it ? Thanks

**Comment by scoter-oracle** [comment]
any feedback @bsk-eduardo-oliveira  ?

**Comment by gvenzl** [comment]
Closing due to lack of response. Please reopen if this is still an issue.
