### ISSUE TITLE
Mising scripts in vagrant-boxes/OracleRAC/scripts/

### ISSUE THREAD

**Issue by kterkal** [oracle/vagrant-boxes#139]
Hello,

I see today that there are missing scripts ( that were there 15th July ) in:

vagrant-boxes/OracleRAC/scripts/

The result is failure  on vagrant up steps.

Missing scripts on 17th July 2019  ( size, name )
	
2.684 		09_gi_installation.sh
2.153 		11_gi_config.sh
151.205 	       13_RDBMS_software_installation.sh
649 		       14_create_database.sh

Scripts that were there on 15th July 2019   (size, name ) :
984 		00_purgelog.sh
1.369 		01_setup_u01.sh
2.921 		02_install_os_packages.sh
2.160 		03_setup_hosts.sh
917 		04_setup_chrony.sh
3.202 		05_setup_shared_disks.sh
4.615 		06_setup_users.sh
1.264 		07_setup_user_equ.expect
1.360 		08_asmfd_label_disk.sh
11.456 		08_asmlib_label_disk.sh
2.684 		09_gi_installation.sh
981 		10_gi_setup.sh
2.153 		11_gi_config.sh
1.275 		12_Make_ASMFD_RECODG.sh
1.291 		12_Make_ASMLib_RECODG.sh
151.205 	13_RDBMS_software_installation.sh
649 		14_create_database.sh
2.401 		15_Check_database.sh
1534.728 	setup.sh

Br, Krešimir

**Comment by rcitton** [comment]
Such script are auto generated. It expected they are not part of the "distribution"

**Comment by kterkal** [comment]
Now I see , in setup.sh .
Thanks!

**Comment by rcitton** [comment]
could you please close the issue :)

rgs
ruggero
