### ISSUE TITLE
ORDS not running

### ISSUE THREAD

**Issue by ecardona29** [oracle/vagrant-boxes#140]
After successful installation and receiving passwords in the install, the database is running but ORDS and JAVA do not seem to be running.

Additionally, start_ORDS.sh is not in the oracle home directory.

**Comment by scoter-oracle** [comment]
Hi,

as already said on my blog, you should only connect to http://localhost:8080/ords from the browser on your host operating-system.
ORDS is now started as a Linux service by systemd so there's no need to have the script.

Simon

**Comment by ecardona29** [comment]
Thank you for your quick reply! Unfortunately, I have tried doing that and it says the site cannot be reached.

**Comment by scoter-oracle** [comment]
Ok, so I need the output of your "vagrant up" execution to understand what it's wrong.
In the meanwhile you can check if your VM is listening on port 8080 by executing:

# netstat -anp |grep 8080

Were all the software files (APEX, ORDS and Oracle XE 18c RPM) there when you executed "vagrant up" ?

**Comment by ecardona29** [comment]
C:\Users\eliza\vagrant-boxes\OracleAPEX>vagrant up
getting Proxy Configuration from Host...
Bringing machine 'oracle-18c-apex' up with 'virtualbox' provider...
==> oracle-18c-apex: Configuring proxy environment variables...
==> oracle-18c-apex: Configuring proxy for Yum...
==> oracle-18c-apex: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> oracle-18c-apex: flag to force provisioning. Provisioners marked to run always will still run.



 netstat -anp|grep 8080
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)

**Comment by ecardona29** [comment]
C:\Users\eliza\vagrant-boxes\OracleAPEX>vagrant up
getting Proxy Configuration from Host...
Bringing machine 'oracle-18c-apex' up with 'virtualbox' provider...
==> oracle-18c-apex: Clearing any previously set forwarded ports...
==> oracle-18c-apex: Clearing any previously set network interfaces...
==> oracle-18c-apex: Preparing network interfaces based on configuration...
    oracle-18c-apex: Adapter 1: nat
==> oracle-18c-apex: Forwarding ports...
    oracle-18c-apex: 1521 (guest) => 1521 (host) (adapter 1)
    oracle-18c-apex: 5500 (guest) => 5500 (host) (adapter 1)
    oracle-18c-apex: 8080 (guest) => 8080 (host) (adapter 1)
    oracle-18c-apex: 22 (guest) => 2222 (host) (adapter 1)
==> oracle-18c-apex: Running 'pre-boot' VM customizations...
==> oracle-18c-apex: Booting VM...
==> oracle-18c-apex: Waiting for machine to boot. This may take a few minutes...
    oracle-18c-apex: SSH address: 127.0.0.1:2222
    oracle-18c-apex: SSH username: vagrant
    oracle-18c-apex: SSH auth method: private key
==> oracle-18c-apex: Machine booted and ready!
==> oracle-18c-apex: Checking for guest additions in VM...
==> oracle-18c-apex: Setting hostname...
==> oracle-18c-apex: Configuring proxy environment variables...
==> oracle-18c-apex: Configuring proxy for Yum...
==> oracle-18c-apex: Mounting shared folders...
    oracle-18c-apex: /vagrant => C:/Users/eliza/vagrant-boxes/OracleAPEX
==> oracle-18c-apex: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> oracle-18c-apex: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by ecardona29** [comment]
[vagrant@oracle-18c-apex ~]$ ps -ef | grep ords
vagrant   4059  3789  0 15:41 pts/0    00:00:00 grep --color=auto ords
[vagrant@oracle-18c-apex ~]$ curl localhost:8080
curl: (7) Failed connect to localhost:8080; Connection refused
[vagrant@oracle-18c-apex ~]$ curl localhost:80
curl: (7) Failed connect to localhost:80; Connection refused
[vagrant@oracle-18c-apex ~]$ ps -ef | grep java
vagrant   4127  3789  0 15:42 pts/0    00:00:00 grep --color=auto java

**Comment by scoter-oracle** [comment]
the output above of "vagrant up" is not related to the first execution, and so, installation of all the components. I would suggest you to re-create your environment with:

vagrant destroy (to destroy the existing environment)

and then follow the installation steps available at https://github.com/oracle/vagrant-boxes/tree/master/OracleAPEX (Getting Started section).

**Comment by scoter-oracle** [comment]
any feedback @ecardona29  ?

**Comment by ecardona29** [comment]
Hi,
I ran the installation again. New Vagrant installation and VM. I followed the directions exactly. The same thing occurred. I still do not have access. I have attached the installer for your reference. I appreciate any feedback because my supervisor and I really don't know why it's not installing appropriately. 
[InstallerFile18cXEAPEX.txt](https://github.com/oracle/vagrant-boxes/files/3335480/InstallerFile18cXEAPEX.txt)

**Comment by scoter-oracle** [comment]
Hi, by checking the log (see in Bold):

==> oracle-18c-apex: Running provisioner: shell...
    oracle-18c-apex: Running: C:/Users/eliza/AppData/Local/Temp/vagrant-shell20190626-5612-pc01nh.sh
    **oracle-18c-apex: ls: cannot access /vagrant/apex_1*.*.zip: No such file or directory**
    oracle-18c-apex: UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
    oracle-18c-apex: bug reports using http://www.info-zip.org/zip-bug.html; see README for details.
    oracle-18c-apex: Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
    oracle-18c-apex:   Default action is to extract files in list, except those in xlist, to exdir;
    oracle-18c-apex:   file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).
    oracle-18c-apex:
    oracle-18c-apex:   -p  extract files to pipe, no messages     -l  list files (short format)
    oracle-18c-apex:   -f  freshen existing files, create none    -t  test compressed archive data
    oracle-18c-apex:   -u  update files, create if necessary      -z  display archive comment only
    oracle-18c-apex:   -v  list verbosely/show version info       -T  timestamp archive to latest
    oracle-18c-apex:   -x  exclude files that follow (in xlist)   -d  extract files into exdir
    oracle-18c-apex: modifiers:
    oracle-18c-apex:   -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
    oracle-18c-apex:   -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
    oracle-18c-apex:   -j  junk paths (do not make directories)   -aa treat ALL files as text
    oracle-18c-apex:   -U  use escapes for all non-ASCII Unicode  -UU ignore any Unicode fields
    oracle-18c-apex:   -C  match filenames case-insensitively     -L  make (some) names lowercase
    oracle-18c-apex:   -X  restore UID/GID info                   -V  retain VMS version numbers
    oracle-18c-apex:   -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
    oracle-18c-apex:   -O CHARSET  specify a character encoding for DOS, Windows and OS/2 archives
    oracle-18c-apex:   -I CHARSET  specify a character encoding for UNIX and other archives
    oracle-18c-apex: See "unzip -hh" or unzip.txt for more help.  Examples:
    oracle-18c-apex:   unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
    oracle-18c-apex:   unzip -p foo | more  => send contents of foo.zip via pipe into program more
    oracle-18c-apex:   unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer

It seems that the apex_*.zip file is not available (* can be 18.2 or 19.1).
I can see that you moved a directory named "apex_19.1" but the automation looks for the .zip file (that you maybe have already extracted).
Instructions report:

4. Download the Oracle APEX into this folder - first time only: https://www.oracle.com/technetwork/developer-tools/apex/downloads/index.html

but do not ask to extract the same.

**Comment by ecardona29** [comment]
I'm glad you said that because I noticed that as well, so I moved the zip files instead and got rid the extracted files in that directory. I ran vagrant provision but that threw some of the same errors. 
[Errors with the zip extraction.txt](https://github.com/oracle/vagrant-boxes/files/3335571/Errors.with.the.zip.extraction.txt)

**Comment by scoter-oracle** [comment]
You have to restart from the beginning.
Run:

# vagrant destroy -f
to cleanup the aborted installation.
Then just put zip and RPM files under the directory and run:

# vagrant up

Do not extract anything, do not put files into under other directories, just keep it easy :)

**Comment by ecardona29** [comment]
Hi,

I think I was making this installation a lot of harder than it was. Thank you so much everything has been installed and configured. 

Thanks again!

**Comment by gvenzl** [comment]
Closing as issue has been resolved.
