### ISSUE TITLE
Why aidanns/vagrant-reload plugin?

### ISSUE THREAD

**Issue by RyanBlace** [oracle/vagrant-boxes#142]
Hi,

I'm wondering why you do this in most of the Vagrantfile(s):
```
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end
```
It doesn't seem like you ever use it.

Thanks,
Ryan

**Comment by gvenzl** [comment]
@scoter-oracle, I believe we added this for some Linux config reload, or similar. Do you still remember?

**Comment by scoter-oracle** [comment]
I've added it because on most of the boxes we update the entire OS (kernel included if available) and, reload, allows to get the boxes correctly booting with latest kernel.
