### ISSUE TITLE
Not able to pull fannel from custom registry

### ISSUE THREAD

**Issue by max201920** [oracle/vagrant-boxes#143]
I have created a custom docker registry and then using kubeadm-registry.sh populated images.
Fannel image is present there . Then I edited kubeadm-setup.sh file as follows.

# variables
#REGISTRY="container-registry.oracle.com/kubernetes"
REGISTRY="localhost:5000"

Then executed it . Master node was created but then node was not ready. with following error 

Command - kubectl describe node

`  Ready            False   Sat, 13 Jul 2019 09:23:35 +0000   Sat, 13 Jul 2019 09:22:11 +0000   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

Kubelet logs were showing following details

```
Jul 13 09:23:25 k8s-node kubelet[23142]: W0713 09:23:25.790554   23142 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 13 09:23:25 k8s-node kubelet[23142]: E0713 09:23:25.792241   23142 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jul 13 09:23:25 k8s-node kubelet[23142]: E0713 09:23:25.940811   23142 kuberuntime_manager.go:714] init container start failed: ImagePullBackOff: Back-off pulling image "container-registry.oracle.com/kubernetes/flannel:v0.10.0"
Jul 13 09:23:25 k8s-node kubelet[23142]: E0713 09:23:25.942262   23142 pod_workers.go:186] Error syncing pod c2edaa89-a54f-11e9-ba45-08002720edbc ("kube-flannel-ds-lkxcl_kube-system(c2edaa89-a54f-11e9-ba45-08002720edbc)"), skipping: failed to "StartContainer" for "install-cni" with ImagePullBackOff: "Back-off pulling image \"container-registry.oracle.com/kubernetes/flannel:v0.10.0\""
Jul 13 09:23:30 k8s-node kubelet[23142]: W0713 09:23:30.795739   23142 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 13 09:23:30 k8s-node kubelet[23142]: E0713 09:23:30.796189   23142 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Jul 13 09:23:35 k8s-node kubelet[23142]: W0713 09:23:35.798471   23142 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 13 09:23:35 k8s-node kubelet[23142]: E0713 09:23:35.806170   23142 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

`

Which setting I am missing which causing kubelet to pull image from container-registry.oracle.com/kubernetes/flannel:v0.10.0 when my local registry is having that image?

**Comment by AmedeeBulle** [comment]
Not sure what's happening here. The standard way of changing the repo is to set `KUBE_REPO_PREFIX` in your environment (See [User's Guide](https://docs.oracle.com/cd/E52668_01/E88884/html/requirements-registry-local.html)).

The easiest way for this vagrant setup is to create the [ContainerRegistry vagrant companion box](https://github.com/oracle/vagrant-boxes/tree/master/ContainerRegistry), that way you can destroy/recreate your cluster in minutes.

**Comment by max201920** [comment]
Thanks for documents @AmedeeBulle . Setting up environment variable as follows solved the issue.
export KUBE_REPO_PREFIX="localhost:5000"

I checked kubeadm-setup.sh there is a code for replacing $REGISTRY with custom $registry. and in Flannel deployment yaml file container-registry.oracle.com/kubernetes is hardcoded. I changing REGISTRY value in kubeadm-setup.sh was wrong step.
