### ISSUE TITLE
Deploying DockerEngine Vagrant box behind proxy

### ISSUE THREAD

**Issue by cramirezoracle** [oracle/vagrant-boxes#147]
Hi Folks,  I'm trying the https://github.com/oracle/vagrant-boxes behind oracle proxy, the Oracle Linux 7 vagrant box works like a charm, but  DockerEngine vagrant box doesn't, I found that Oracle Linux 7 Vagrantfile has vagrant-proxyconf instructions, Who could update the DockerEngine box's Vagrantfile?, thanks in advance

**Comment by AmedeeBulle** [comment]
Closing as #149 has been merged
