### ISSUE TITLE
While creating the kubernetes we are geeting bleow error 

### ISSUE THREAD

**Issue by rishtham** [oracle/vagrant-boxes#151]
Hi , 
Can you help me out to fix this . 
Trying to pull repository container-registry.oracle.com/kubernetes/kube-proxy ...
manifest for container-registry.oracle.com/kubernetes/kube-proxy:v1.12.10 not found
[ERROR] docker cannot pull kube-proxy:v1.12.10 from container-registry.oracle.com/kubernetes registry

Thanks, 
Rishi~

**Comment by AmedeeBulle** [comment]
Kubernetes 1.12.10 has just been released, but it seems container images are not on the registry yet.

I am checking with the development / release team to see what happened.

In the meantime you should be able to install the previous version by having 
```
K8S_VERSION=1.12.7
```
in your `.env.local` config file.

**Comment by AmedeeBulle** [comment]
It might take a bit of time to publish the containers, we are looking at removing the 1.12.10 rpms to avoid this issue.

For the time being you will have to use the above workaround.

**Comment by AmedeeBulle** [comment]
The Kubernetes 1.12.10 RPMs have been removed from the public yum; I verified the Vagrant boxes and it all works again as it should.

Closing this issue -- don't hesitate to re-open if needed.
(You will need to destroy / recreate your boxes as they have the faulty RPMs installed)
