### ISSUE TITLE
Unable to Connect via SQLDeveloper from host machine (Mac)

### ISSUE THREAD

**Issue by KaiOnGitHub** [oracle/vagrant-boxes#159]
It seems my installation worked fine but when I try to connect to the database I get this Error from SQLDeveloper:
![image](https://user-images.githubusercontent.com/50620424/68387713-3cb16100-015f-11ea-858d-749c2280a297.png)
 
If I click again I get another error:
![image](https://user-images.githubusercontent.com/50620424/68387722-48048c80-015f-11ea-8cb5-2334a5140bce.png)

a textfile with the whole console output after vagrant up:
[vagrant up.txt](https://github.com/oracle/vagrant-boxes/files/3819491/vagrant.up.txt)

and some extracts as screenshots:
![image](https://user-images.githubusercontent.com/50620424/68387998-ee509200-015f-11ea-9df9-9fa2ef4d5922.png)
![image](https://user-images.githubusercontent.com/50620424/68387982-e4c72a00-015f-11ea-9b82-5d8ad3fdccf4.png)
![image](https://user-images.githubusercontent.com/50620424/68387819-8601b080-015f-11ea-9644-7598c88647b5.png)

I installed a plugin for the guest additions following this guide: https://www.serverlab.ca/tutorials/virtualization/how-to-auto-upgrade-virtualbox-guest-additions-with-vagrant/

**Comment by gvenzl** [comment]
As a matter of fact, the installation has failed. You can see that on the red output of the last screenshot:

```
    oracle11g-xe-vagrant: INSTALLER: Oracle directories created
    oracle11g-xe-vagrant: unzip:  cannot find or open /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip, /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip.zip or /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip.ZIP.
    oracle11g-xe-vagrant: INSTALLER: Oracle software installed
    oracle11g-xe-vagrant: sudo
    oracle11g-xe-vagrant: :
    oracle11g-xe-vagrant: /etc/init.d/oracle-xe: command not found
```

You have to copy the rpm.zip file into the vagrant directory where you call `vagrant up`, as per the [Getting Started](https://github.com/oracle/vagrant-boxes/tree/master/OracleDatabase#getting-started).

However, there is a good ER to change the script to make it clear that the installation has failed.

**Comment by KaiOnGitHub** [comment]
@gvenzl I was uncertain if that red line matters. But where do I find the file `oracle-xe-11.2.0-1.0.x86_64.rpm.zip`? 

On the [website](https://www.oracle.com/database/technologies/oracle-database-software-downloads.html) that is linked in the getting started you only find `linux.zseries64_11gR2_database_1of2.zip` and `linux.zseries64_11gR2_database_2of2.zip` for 11.2.0.2.0

I manually extracted the files from those zip files in the directory `/vagrant-boxes/OracleDatabase/11.2.0.2`

**Comment by PaulNeumann** [comment]
@KaiOnGitHub 
Near the bottom of the linked web page, there's a heading called "Oracle Database Express Edition". Under that heading, there's an "Oracle Database 11g Release 2 Express Edition for Linux x86 and Windows" link. If you click on that link, it will open the Oracle Database XE Prior Release Archive page. To download the installer zip file, select the "Oracle Database 11gR2 Express Edition for Linux x64" link.

I hope this helps!

**Comment by KaiOnGitHub** [comment]
Thank you Paul, it works!

That link is very hidden.
