### ISSUE TITLE
Virtual Machine times out on start and doesnt create

### ISSUE THREAD

**Issue by varianjv** [oracle/vagrant-boxes#162]
Hi 
I have done the following on my Macbook and it works fine
Now trying to do the same on my Windows Machine and having trouble
Windows 10 64bit

I have installed vagrant_2.2.6_x86_64 & VirtualBox-6.0.14-133895-Win
I git cloned https://github.com/oracle/vagrant-boxes.git

In the folder vagrant-boxes\OracleDatabase\12.2.0.1
I run the vagrant up command and get the following
![vagrant1](https://user-images.githubusercontent.com/43672101/68600980-59210680-049b-11ea-8ad1-3ff924e0fd89.png)

Virtualbox just sits at

![vagrant2](https://user-images.githubusercontent.com/43672101/68601033-7229b780-049b-11ea-848c-f9fb0cd194a6.png)

As I said. Zero issue on my mac however my windows 10 machine is giving me this issue

Can anyone help

**Comment by PaulNeumann** [comment]
@varianjv
Have you tried any other VirtualBox VMs on your Windows computer? If other VirtualBox VMs work, then you can ignore the rest of this message. But if this problem affects all VMs, here are a couple of things to look at:
1. If your Windows computer has an Intel CPU, make sure that VT-x is enabled in the BIOS. I'd expect to see an error message if this were the problem, but it's worth checking.
2. If Hyper-V, or any Windows feature that depends on Hyper-V, is installed, that can cause problems for VirtualBox.  Features that use Hyper-V include Application Guard, Credential Guard, Device Guard, and Windows Sandbox.  There's a [**long** discussion about this](https://forums.virtualbox.org/viewtopic.php?f=6&t=90853) in the VirtualBox forums on virtualbox.org.

I hope this helps!

**Comment by varianjv** [comment]
@PaulNeumann Thanks for this. I had HyperV disabled via turn Windows Features on or off
However apparently this isnt enough and i needed to run the following command to properly disable
bcdedit /set hypervisorlaunchtype off

Found it [here](https://blog.zeddba.com/2017/09/25/disabling-microsofts-hyper-v-to-use-oracles-virtualbox/)

**Comment by PaulNeumann** [comment]
@varianjv Excellent! I'm glad it's working for you now.
