### ISSUE TITLE
APEX box - Minor issue with tablespace datafile directory

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#163]
The `apex.sh` script creates a tablespace called "APEX". The tablespace's datafile, `apex01.dbf`, is created in the directory `/opt/oracle/oradata/XE`. This is the directory for the CDB's datafiles. Since APEX is installed in the PDB, its datafiles ideally should be in the PDB's datafile directory, `/opt/oracle/oradata/XE/XEPDB1`. This doesn't affect the functionality of the box, but it's the kind of thing that DBAs really don't like.

Changing line 44 of `apex.sh` from
```
CREATE TABLESPACE apex DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/apex01.dbf'
```
to
```
CREATE TABLESPACE apex DATAFILE '$ORACLE_BASE/oradata/$ORACLE_SID/$ORACLE_PDB/apex01.dbf'
```
would correct this.

If you agree that this is a legitimate issue, and that the suggested solution is correct, I'd be happy to submit a PR.

**Comment by gvenzl** [comment]
Yes, and yes @PaulNeumann :)

**Comment by PaulNeumann** [comment]
@gvenzl Thank you, sir. PR submitted.

**Comment by gvenzl** [comment]
Merged, thanks @PaulNeumann!
