### ISSUE TITLE
Downloaded 12.2, but is not recognized by vagrant

### ISSUE THREAD

**Issue by pven** [oracle/vagrant-boxes#165]
I've downloaded linuxx64_12201_database.zip from https://www.oracle.com/database/technologies/oracle12c-linux-12201-downloads.html . I moved the file to OracleDG\ORCL_software

When I start 'vagrant up' I get a 'ERROR: db_software does not exist'. I renamed the file to LINUX.X64_122010_db_home.zip but that gives the same error. I did a 'git pull' to be sure, but that does not solve it.

How can I get this up-and-running?

**Comment by gvenzl** [comment]
@critton, can you please take a look?

**Comment by pven** [comment]
Ok, thanks
