### ISSUE TITLE
sqlplus not found

### ISSUE THREAD

**Issue by pierre03** [oracle/vagrant-boxes#169]
Hi, 
I want to prepare a database server with oracle xe 11.2.0.2, i can now connect to the db from another server with sql developper, but to initialize the database tables, on the local database server, i did't find the sqlplus to run the sql scripts. 
So i have downloaded the packages:
- oracle-instantclient19.5-basic-19.5.0.0.0-1.x86_64.rpm
- oracle-instantclient19.5-sqlplus-19.5.0.0.0-1.x86_64.rpm
but these packages can not be installed on the server, i got the error message: 
```
oracle-xe conflicts with oracle-instantclient***x86_64
oracle-instantclient**-basic >= 19.5.0.0.0 is needed by oracle-instantclient19.5-sqlplus-***x86_64
```
Can you tell me how to resolve this problem, please?
Thank you.

**Comment by PaulNeumann** [comment]
@pierre03,
The database utilities, including sqlplus, are already installed in the Vagrant box. However, by default, the vagrant user doesn't have the necessary Oracle Database environment variables set to run them.  There are two ways to run sqlplus in an ssh session:
1. You can change to the oracle user by running `sudo su - oracle`.  The oracle user has the necessary environment variables set, so it can run sqlplus.
1. To run sqlplus as the vagrant user, first run `. /u01/app/oracle/product/11.2.0/xe/bin/oracle_env.sh`. This script sets the needed environment variables.  (If you want to do this often, you might consider adding this command to the vagrant user's `.bash_profile` file.)

I hope this helps!
