### ISSUE TITLE
disable vagrant-vguest plugin

### ISSUE THREAD

**Issue by bgraef** [oracle/vagrant-boxes#173]
Hi -

While testing the Vagrantfile, found that the _vagrant up_ would fail when updating the vguest as my environment has the vagrant-vguest plugin installed.

I added the following code to the Vagrantfile to disable the auto_update feature of this plugin as it does not appear you are using shared_folders or other vguest features in your deployment.

`# Disable the vagrant-vguest auto_update plugin`
` if Vagrant.has_plugin?("vagrant-vbguest")`
`   config.vbguest.auto_update = false`
` end`
 
Once this was added, _vagrant up_ completed successfully.

**Comment by gvenzl** [comment]
Thanks @bgraef for reporting this!

Hi @scoter-oracle, could you please take a look at this and whether this should be an issue or not, and if, whether we should include the lines above?

**Comment by ethanmdavidson** [comment]
I think this is the same problem as #137, and the solution is the same: when you build the base box, install the guest additions via yum (**not** via the ISO), so that the vagrant-vbguest plugin can properly manage it. The plugin offers several advantages, the main one being that the proper version of guestadditions will be installed every time, regardless of what version the box was built with, and will always match the version used by the host.

**Comment by PaulNeumann** [comment]
@scoter-oracle Is it even possible to install the VirtualBox 6.x Guest Additions via yum? It looks to me like the VirtualBox packages available in the ol7_developer yum repo are full VirtualBox installers, not the GAs:
```
[root@oracle-18c-apex vagrant]# yum list VirtualBox*
Available Packages
VirtualBox-5.1.x86_64                                 5.1.30_118389_el7-1                                  ol7_developer
VirtualBox-5.2.x86_64                                 5.2.26_128414_el7-1                                  ol7_developer
VirtualBox-6.0.x86_64                                 6.0.10_132072_el7-1                                  ol7_developer
[root@oracle-18c-apex vagrant]# yum info VirtualBox-6.0
Available Packages
Name        : VirtualBox-6.0
Arch        : x86_64
Version     : 6.0.10_132072_el7
Release     : 1
Size        : 110 M
Repo        : ol7_developer/x86_64
Summary     : Oracle VM VirtualBox
URL         : http://www.virtualbox.org/
License     : GPLv2
Description : VirtualBox is a powerful PC virtualization solution allowing
            : you to run a wide range of PC operating systems on your Linux
            : system. This includes Windows, Linux, FreeBSD, DOS, OpenBSD
            : and others. VirtualBox comes with a broad feature set and
            : excellent performance, making it the premier virtualization
            : software solution on the market.
```
The GAs would be much smaller than 110 MB (the ISO is about half that size), and the description doesn't mention the Guest Additions.

**Comment by fnordfish** [comment]
Short reminder that Vagrant merges Vagrantfiles (https://www.vagrantup.com/docs/vagrantfile/#load-order-and-merging) - just create a `~/.vagrant.d/Vagrantfile` and put your plugin configs in there:

```ruby
Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")
end
```

**Comment by scoter-oracle** [comment]
Updated boxes now contain "kernel-uek-devel" and "kernel-devel" package so in case of updated kernel the VirtualBox guest-additions are automatically recompiled on boot.
