### ISSUE TITLE
Incorrect Oracle Linux versions in README.md files

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#174]
The `README.md` files for 3 of the boxes refer to an incorrect or outdated Oracle Linux version:

* `OracleLinux/6/README.md` states that the box is based on Oracle Linux 7, instead of Oracle Linux 6.
* `OracleDatabase/11.2.0.2/README.md` and `OracleDatabase/12.2.0.1/README.md` state that the boxes are based on Oracle Linux 7.3. This is outdated. To be consistent with the other boxes, these READMEs should refer to Oracle Linux 7.

If you agree that these files should be updated as suggested, I'd be happy to submit a PR.

**Comment by totalamateurhour** [comment]
Please go ahead and submit a PR. thanks!
