### ISSUE TITLE
Vagrant 2.2.6 doesn't work with VirtualBox 6.1.0

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#178]
VirtualBox 6.1.0 has been released. Unfortunately, Vagrant 2.2.6 doesn't work with this new release. This isn't an issue with this repository, but it may affect people using these boxes. It should be fixed in the next release of Vagrant (see [https://github.com/hashicorp/vagrant/issues/11249](https://github.com/hashicorp/vagrant/issues/11249)), but here's how to work around the problem in the meantime.

Credits:
- @scoter-oracle [blogged about a very similar issue last year](https://blogs.oracle.com/scoter/getting-vagrant-220-working-with-virtualbox-60-beta1).
- @briancain has developed a fix for the next Vagrant release (see [https://github.com/briancain/vagrant/commit/fb4e6985e142da56bad143d70600cd3695c91757](https://github.com/briancain/vagrant/commit/fb4e6985e142da56bad143d70600cd3695c91757))

The workaround requires 3 changes.

First, in the file `/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/plugin.rb`, add a line at the end of the Driver module for VirtualBox 6.1, as follows. (On Windows, the file location is `C:\HashiCorp\Vagrant\embedded\gems\2.2.6\gems\vagrant-2.2.6\plugins\providers\virtualbox\plugin.rb`.)

```ruby
module Driver
  autoload :Meta, File.expand_path("../driver/meta", __FILE__)
  autoload :Version_4_0, File.expand_path("../driver/version_4_0", __FILE__)
  autoload :Version_4_1, File.expand_path("../driver/version_4_1", __FILE__)
  autoload :Version_4_2, File.expand_path("../driver/version_4_2", __FILE__)
  autoload :Version_4_3, File.expand_path("../driver/version_4_3", __FILE__)
  autoload :Version_5_0, File.expand_path("../driver/version_5_0", __FILE__)
  autoload :Version_5_1, File.expand_path("../driver/version_5_1", __FILE__)
  autoload :Version_5_2, File.expand_path("../driver/version_5_2", __FILE__)
  autoload :Version_6_0, File.expand_path("../driver/version_6_0", __FILE__)
  autoload :Version_6_1, File.expand_path("../driver/version_6_1", __FILE__)
end
```

Second, in the file `/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/meta.rb`, add a line at the end of the driver_map section for VirtualBox 6.1, as follows. (On Windows, the file location is `C:\HashiCorp\Vagrant\embedded\gems\2.2.6\gems\vagrant-2.2.6\plugins\providers\virtualbox\driver\meta.rb`.)

```ruby
driver_map   = {
  "4.0" => Version_4_0,
  "4.1" => Version_4_1,
  "4.2" => Version_4_2,
  "4.3" => Version_4_3,
  "5.0" => Version_5_0,
  "5.1" => Version_5_1,
  "5.2" => Version_5_2,
  "6.0" => Version_6_0,
  "6.1" => Version_6_1,
}
```

Finally, create a **new** file called `version_6_1.rb` in the directory `/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver`. (On Windows, create this file in the folder `C:\HashiCorp\Vagrant\embedded\gems\2.2.6\gems\vagrant-2.2.6\plugins\providers\virtualbox\driver`.) In this new file, paste the content from [here](https://raw.githubusercontent.com/briancain/vagrant/fb4e6985e142da56bad143d70600cd3695c91757/plugins/providers/virtualbox/driver/version_6_1.rb).

With these 3 changes, Vagrant 2.2.6 will work with VirtualBox 6.1.0. I hope this helps!

**Comment by piotr-cz** [comment]
Thanks for sharing!

**Comment by rodrigoprimo** [comment]
Workaround available here: https://github.com/oracle/vagrant-boxes/issues/178#issue-536720633

**Comment by MasterCATZ** [comment]
Thank you

**Comment by RvstFyth** [comment]
Nice, thanks for the workaround!
For Arch linux the paths where a bit different though:  

`/opt/vagrant/embedded/gems/gems/vagrant-2.2.6/plugins/providers/virtualbox/plugin.rb`
`/opt/vagrant/embedded/gems/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/meta.rb`

**Comment by jonroberts24** [comment]
Do you know when the next version that will work with VirtualBox will be out? Are we talking weeks / months? thanks

**Comment by PaulNeumann** [comment]
@jonroberts24 Only the Vagrant team can answer that. The only indication I've seen is @briancain's [comment on the issue](https://github.com/hashicorp/vagrant/issues/11249#issuecomment-565214999) in the Vagrant repository.

**Comment by ZiluckMichael** [comment]
@PaulNeumann When I perform the steps you mentioned, I get the following error message:
```
A customization command failed:

["modifyvm", :id, "--clipboard", "bidirectional"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "ce8a3576-201c-11ea-978f-2e728ce88125", "--clipboard", "bidirectional"]
```
Any ideas how I might get this resolved without disabling the bidirectional clipboard?

**Comment by PaulNeumann** [comment]
@ZiluckMichael I don't know; I'm sorry. I suggest asking in the [hashicorp/vagrant repository](https://github.com/hashicorp/vagrant). The thread for the VirtualBox 6.1.0 issue is at https://github.com/hashicorp/vagrant/issues/11249.

**Comment by scoter-oracle** [comment]
While waiting for a fix from Vagrant you can apply that change manually by using "VBoxManage" CLI:

# vboxmanage modifyvm <uuid/name> --clipboard-mode bidirectional

The option "--clipboard" has change to "--clipboard-mode" on 6.1 VirtualBox release.

**Comment by armenr** [comment]
Wow. The first post of this issue saved my butt.

When can we expect a stable update from the Vagrant team?

**Comment by scoter-oracle** [comment]
@karlbunch consider my update above for the Vagrant release supporting VirtualBox 6.1.0 (related to the clipboard change)

**Comment by rroman81** [comment]
I am getting an error when attempting to run Vagrant after inserting the Version_6_1 driver files in 2.2.6 folders.  
```zsh
Vagrant failed to initialize at a very early stage:

The directory Vagrant will use to store local environment-specific
state is not accessible. The directory specified as the local data
directory must be both readable and writable for the user that is
running Vagrant.

Local data directory: /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/.vagrant
```

**Comment by rroman81** [comment]
Newbie error.  I had to run the vagrant command inside the working folder and fix my ruby error :)

**Comment by paolodenti** [comment]
thank you

**Comment by Redsandro** [comment]
Thank you :+1: 

Don't forget the newly created file needs to be readable by all (e.g. `644`), in case you have a different `umask` when running `sudo`.

**Comment by jimfrenette** [comment]
Thanks for this!
In fedora 31, the paths where:
/usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/providers/virtualbox/plugin.rb
/usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/meta.rb

**Comment by riksanyal** [comment]
> While waiting for a fix from Vagrant you can apply that change manually by using "VBoxManage" CLI:
> 
> `vboxmanage modifyvm <uuid/name> --clipboard-mode bidirectional`
> 
> The option "--clipboard" has changed to "--clipboard-mode" on 6.1 VirtualBox release.

I still get the original error even after I run this @scoter-oracle

**Comment by MalikKhattak** [comment]
This is a great solution. Only have to be sudo before making changes. Thank you

**Comment by pchng** [comment]
@PaulNeumann thank you very much for the very detailed instructions, both for Linux and Windows! Super easy to follow and understand +1

**Comment by omgMerrickD** [comment]
Thank you so much for this @PaulNeumann!  Cheers!

**Comment by michelvermeulen** [comment]
Thanks so much! Works great :)

**Comment by mikehomee** [comment]
Thank you! Works like a charm!

**Comment by Lewiscowles1986** [comment]
My solution was to visit https://www.virtualbox.org/wiki/Download_Old_Builds_6_0 get supported versions with the highest patch and not manually patch vendor libraries on my computer.

While I would hope Vagrant will patch soon, so I can upgrade both; removing the at-present unsupported version, in favor of 6.0 (October 2019, it's not exactly old); seemed a responsible route.

**Comment by CYIMANA-Faisal** [comment]
> VirtualBox 6.1.0 has been released. Unfortunately, Vagrant 2.2.6 doesn't work with this new release. This isn't an issue with this repository, but it may affect people using these boxes. It should be fixed in the next release of Vagrant (see [hashicorp/vagrant#11249](https://github.com/hashicorp/vagrant/issues/11249)), but here's how to work around the problem in the meantime.
> 
> Credits:
> 
> * @scoter-oracle [blogged about a very similar issue last year](https://blogs.oracle.com/scoter/getting-vagrant-220-working-with-virtualbox-60-beta1).
> * @briancain has developed a fix for the next Vagrant release (see [briancain/vagrant@fb4e698](https://github.com/briancain/vagrant/commit/fb4e6985e142da56bad143d70600cd3695c91757))
> 
> The workaround requires 3 changes.
> 
> First, in the file `/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/plugin.rb`, add a line at the end of the Driver module for VirtualBox 6.1, as follows. (On Windows, the file location is `C:\HashiCorp\Vagrant\embedded\gems\2.2.6\gems\vagrant-2.2.6\plugins\providers\virtualbox\plugin.rb`.)
> 
> ```ruby
> module Driver
>   autoload :Meta, File.expand_path("../driver/meta", __FILE__)
>   autoload :Version_4_0, File.expand_path("../driver/version_4_0", __FILE__)
>   autoload :Version_4_1, File.expand_path("../driver/version_4_1", __FILE__)
>   autoload :Version_4_2, File.expand_path("../driver/version_4_2", __FILE__)
>   autoload :Version_4_3, File.expand_path("../driver/version_4_3", __FILE__)
>   autoload :Version_5_0, File.expand_path("../driver/version_5_0", __FILE__)
>   autoload :Version_5_1, File.expand_path("../driver/version_5_1", __FILE__)
>   autoload :Version_5_2, File.expand_path("../driver/version_5_2", __FILE__)
>   autoload :Version_6_0, File.expand_path("../driver/version_6_0", __FILE__)
>   autoload :Version_6_1, File.expand_path("../driver/version_6_1", __FILE__)
> end
> ```
> 
> Second, in the file `/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/meta.rb`, add a line at the end of the driver_map section for VirtualBox 6.1, as follows. (On Windows, the file location is `C:\HashiCorp\Vagrant\embedded\gems\2.2.6\gems\vagrant-2.2.6\plugins\providers\virtualbox\driver\meta.rb`.)
> 
> ```ruby
> driver_map   = {
>   "4.0" => Version_4_0,
>   "4.1" => Version_4_1,
>   "4.2" => Version_4_2,
>   "4.3" => Version_4_3,
>   "5.0" => Version_5_0,
>   "5.1" => Version_5_1,
>   "5.2" => Version_5_2,
>   "6.0" => Version_6_0,
>   "6.1" => Version_6_1,
> }
> ```
> 
> Finally, create a **new** file called `version_6_1.rb` in the directory `/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver`. (On Windows, create this file in the folder `C:\HashiCorp\Vagrant\embedded\gems\2.2.6\gems\vagrant-2.2.6\plugins\providers\virtualbox\driver`.) In this new file, paste the content from [here](https://raw.githubusercontent.com/briancain/vagrant/fb4e6985e142da56bad143d70600cd3695c91757/plugins/providers/virtualbox/driver/version_6_1.rb).
> 
> With these 3 changes, Vagrant 2.2.6 will work with VirtualBox 6.1.0. I hope this helps!

ooooooooooooo yeah. Now you are my hero. Thanks, buddy

**Comment by ArturoTarinVillaescusa** [comment]
Thank you, it worked!

**Comment by netsensei** [comment]
Works for me! thanks!

Any Fedora 31 users who might stumble across this:

I'm on Fedora 3.1 which pushes kernel 5.4.x on `sudo dnf update`. VirtualBox 6.0 won't work under kernel 5.4 because the `vboxdrv` plugin will complain about incompatible kernel modules. Trying to compile the modules will fail since kernel 5.4 is only supported as of VirtualBox 6.1

So, that leaves you with two options:

* Manually apply this to get Vagrant 2.2.6 to support VirtualBox 6.1
* Don't use kernel 5.4 and stay on the 5.3 branch until Hashicorp pushes a new release which includes support for Virtualbox 6.1 (see: https://github.com/hashicorp/vagrant/issues/11249 which is already fixed and ready for shipment)

**Comment by charlmert** [comment]
I knew you guys would create a freaking brilliant fix for this,
Thanks you guys works perfectly.

**Comment by Artistan** [comment]
fix still works, thanks!

**Comment by SmellyFish** [comment]
The fix worked, thanks! For step 3, make sure you read the instructions carefully and put the linked contents into `version_6_1.rb`. I read a little too fast and left the file blank which produced the following error:
```
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/version_6_1 (LoadError)
```

**Comment by skobkin** [comment]
Is there an easy way to patch the binary provided here: `https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_linux_amd64.zip`
?

**Comment by ivanorusso** [comment]
Thank you, it worked like a charm

**Comment by jabenninghoff** [comment]
Here is a patch file to implement the workaround above: https://gist.github.com/jabenninghoff/a1680f5a7146370b461bb1c38fa8e14f

**Comment by rbreaves** [comment]
I think you are better off remapping 6.1 to 6.0. I have several plugins that need to initialize as well and I think they fail due to the mapping of 6.1 to 6.1.

macOS: /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/meta.rb
Windows: C:\HashiCorp\Vagrant\embedded\gems\2.2.6\gems\vagrant-2.2.6\plugins\providers\virtualbox\driver\meta.rb
```
"6.1" => Version_6_0,
```

**Comment by yveshwang** [comment]
Thank you!

**Comment by adeoke** [comment]
Vagrant 2.2.7 now released. Appears to resolve my problem with virtualbox 6.1.x not being recognised.

**Comment by machielg** [comment]
Fixed with GH-11250

> Vagrant 2.2.7 now released. Appears to resolve my problem with virtualbox 6.1.x not being recognised.

**Comment by scoter-oracle** [comment]
Vagrant 2.2.7 adds support for VirtualBox 6.1 - https://github.com/hashicorp/vagrant/blob/v2.2.7/CHANGELOG.md 
Closing the issue.

**Comment by timka** [comment]
2.2.7 doesn't work for me
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'kane_project/windows-10' version '1903' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 5986 (guest) => 55986 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
A customization command failed:

["modifyvm", :id, "--clipboard", "bidirectional"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "ce2ae2de-d509-46e4-82ac-11df167cf2d5", "--clipboard", "bidirectional"]

Stderr: Oracle VM VirtualBox Command Line Management Interface Version 6.1.2
(C) 2005-2020 Oracle Corporation
All rights reserved.

Usage:
# ...

VBoxManage: error: Unknown option: --clipboard
>

Please fix this customization and try again.

$ vagrant -v
Vagrant 2.2.7
```

**Comment by scoter-oracle** [comment]
@timka this issue has to be reported to the vagrant-project. I already shared this issue with them but it seems that the same had been ignored.

**Comment by timka** [comment]
@scoter-oracle Ah, wrong issue. Sorry for that

**Comment by scoter-oracle** [comment]
@timka I've talked with Vagrant guys, it seems that the "clipboard" mode is not an option managed by Vagrant but custom-code that you have into your box definition. So, you can evaluate to change the "--clipboard" to "--clipboard-mode" into your code. BTW, I've also talked with VBox engineering and we'll get back the support for also the older syntax. Thanks

**Comment by dkalaluhi** [comment]
Still an issue on fedora 31 with the repo version they have. Workaround does indeed work, but in the end, too many wonky things going on...just ended up going with 2.2.7 and fixed everything

**Comment by thebleshbanz** [comment]
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/providers/virtualbox/driver/meta (LoadError)

i am getting this error when run vagrant uo command in ubuntu 18.04

and i also give 644 permission to new created file

**Comment by mojili** [comment]
@PaulNeumann 
Thank you. The provided solution was great

**Comment by HenryPineda** [comment]
Thanks for sharing. It worked for me!

**Comment by blecx** [comment]
Hi,

on debin the pathes are:
/usr/share/rubygems-integration/all/gems/vagrant-2.2.3/plugins/providers/virtualbox/driver/meta.rb 
/usr/share/rubygems-integration/all/gems/vagrant-2.2.3/plugins/providers/virtualbox/driver/version_6_1.rb 

rest as decribed
