### ISSUE TITLE
set -e breaks 18.3.0 database box build

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#179]
In #161, `set -e` was added to the `install.sh` scripts for the single instance database boxes in order to abort the installation on any error. Unfortunately, this breaks the build for the 18.3.0 database box, because the `runInstaller` script that installs Oracle Database returns a non-zero exit status when prerequisites are ignored.

Line 64 of `install.sh` for the 18.3.0 box calls `runInstaller` with the `-ignorePrereqFailure` parameter. This is necessary because any VM with less than 8 GB of RAM would fail the prerequisite check. However, when `runInstaller` is called with this parameter, it always returns a non-zero exit status. Here are the last few lines from an example `installActions.log` file:

```
INFO:  [Dec 14, 2019 11:07:20 AM] Adding ExitStatus SUCCESS_WITH_WARNINGS to the exit status set
INFO:  [Dec 14, 2019 11:07:20 AM] Finding the most appropriate exit status for the current application
INFO:  [Dec 14, 2019 11:07:20 AM] Exit Status is 6
INFO:  [Dec 14, 2019 11:07:20 AM] List of warnings encountered in this Application:
INFO:  [Dec 14, 2019 11:07:20 AM] PREREQUISITES_IGNORED
INFO:  [Dec 14, 2019 11:07:20 AM] Shutdown Oracle Database 18c Installer
```

So, even though the software was installed successfully, `runInstaller` exits with a status of 6, because prerequisites were ignored. This causes `install.sh` to abort.

This affects **only** the 18.3.0 box. The other single instance database boxes build fine with `set -e`.

To correct the issue, I suggest modifying the `install.sh` script for the 18.3.0 box so that it aborts if `runInstaller` returns any exit status other than 6:

```bash
# runInstaller returns exit status 6 when prereqs are ignored
set +e
su -l oracle -c "yes | $ORACLE_HOME/runInstaller -silent -ignorePrereqFailure -waitforcompletion -responseFile /vagrant/ora-response/db_install.rsp"
if [ $? -ne 6 ]
then
  exit 1
fi
set -e
```

I've verified that this resolves the problem. If you agree that this is a legitimate issue, and that this approach is correct, I'd be happy to submit a PR.

**Comment by gvenzl** [comment]
Merged.
