### ISSUE TITLE
OracleDG vagrant up fails due to a missing standby disk

### ISSUE THREAD

**Issue by mvelikikh** [oracle/vagrant-boxes#182]
I got the following error while running 'vagrant up' for Oracle Data Guard boxes:
```
==> node2: Running 'pre-boot' VM customizations...
A customization command failed:

["storageattach", :id, "--storagectl", "SATA Controller", "--port", 2, "--device", 0, "--type", "hdd", "--medium", "./standby_u01.vdi", "--nonrotational", "on"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "da6521fd-de5b-4ef5-a09b-6c73f5efa3dd", "--storagectl", "SATA Controller", "--port", "2", "--device", "0", "--type", "hdd", "--medium", "./standby_u01.vdi", "--nonrotational", "on"]

Stderr: VBoxManage.exe: error: Could not find file for the medium 'C:\vagrant\repos\vagrant-boxes\OracleDG\standby_u01.vdi' (VERR_FILE_NOT_FOUND)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 191 of file VBoxManageDisk.cpp
VBoxManage.exe: error: Invalid UUID or filename "./standby_u01.vdi"
>
```

As you can see, the standby u01 disk is not created. It is happened due to the following block https://github.com/oracle/vagrant-boxes/blob/62a1f8721b208922566b770523181b89ace0c0d6/OracleDG/Vagrantfile#L339-L342
We are checking **var_vm1_u01_disk** and then are trying to create **var_vm2_u01_disk**, so that we are just checking the wrong disk. I have already amended that File.exist condition in my lab and was able to create the standby machine successfully.
I would be happy to submit a PR if you do not mind.

**Comment by rcitton** [comment]
Hello Mvelikikh, 

I can not reproduce at all:

(...)
    node1: -----------------------------------------------------------------
    node1: INFO: 2019-12-21 09:22:22: Running user-defined post-setup scripts
    node1: -----------------------------------------------------------------
==> node2: Importing base box 'ol7-latest'...
==> node2: Matching MAC address for NAT networking...
==> node2: Setting the name of the VM: ol7-dg-standby
==> node2: Fixed port collision for 22 => 2222. Now on port 2204.
==> node2: Clearing any previously set network interfaces...
==> node2: Preparing network interfaces based on configuration...
    node2: Adapter 1: nat
    node2: Adapter 2: hostonly
    node2: Adapter 3: intnet
==> node2: Forwarding ports...
    node2: 22 (guest) => 2204 (host) (adapter 1)
==> node2: Running 'pre-boot' VM customizations...
==> node2: Booting VM...
==> node2: Waiting for machine to boot. This may take a few minutes...
    node2: SSH address: 127.0.0.1:2204
    node2: SSH username: vagrant
    node2: SSH auth method: private key
    node2: 
    node2: Vagrant insecure key detected. Vagrant will automatically replace
    node2: this with a newly generated keypair for better security.
    node2: 
    node2: Inserting generated public key within guest...
    node2: Removing insecure key from the guest if it's present...
    node2: Key inserted! Disconnecting and reconnecting using new SSH key...
==> node2: Machine booted and ready!
==> node2: Checking for guest additions in VM...
==> node2: Setting hostname...
==> node2: Configuring and enabling network interfaces...
==> node2: Configuring proxy environment variables...
==> node2: Configuring proxy for Yum...
==> node2: Mounting shared folders...
    node2: /vagrant => /u01/vagrant-boxes/OracleDG
    node2: /vagrant_config => /u01/vagrant-boxes/OracleDG/config
    node2: /vagrant_scripts => /u01/vagrant-boxes/OracleDG/scripts
    node2: /vagrant_userscripts => /u01/vagrant-boxes/OracleDG/userscripts
==> node2: Running provisioner: shell...
    node2: Running: inline script
==> node2: Running provisioner: shell...
    node2: Running: /tmp/vagrant-shell20191221-65427-1h8ndmb.sh
(...)

Everything is working properly.

**Comment by mvelikikh** [comment]
Hi rcitton,
Did you have the ./standby_u01.vdi present on your machine before you ran the vagrant up command?
It should not fail in this case. I cloned the vagrant repo and followed the installation instructions - there was no standby_u01.vdi and it is not created in the Vagrantfile.
The Vagrantfile has the following lines for node1:
https://github.com/oracle/vagrant-boxes/blob/62a1f8721b208922566b770523181b89ace0c0d6/OracleDG/Vagrantfile#L299-L302
The corresponding lines for node2 are:

https://github.com/oracle/vagrant-boxes/blob/62a1f8721b208922566b770523181b89ace0c0d6/OracleDG/Vagrantfile#L339-L342

Notice please that we are checking in both cases var_vm1_u01_disk, which is coming from https://github.com/oracle/vagrant-boxes/blob/62a1f8721b208922566b770523181b89ace0c0d6/OracleDG/Vagrantfile#L89
which is set to ./primary_u01.vdi by default https://github.com/oracle/vagrant-boxes/blob/62a1f8721b208922566b770523181b89ace0c0d6/OracleDG/config/vagrant.yml#L7
Those are the only lines that have createhd commands for the u01 disks.
That check works fine only for node1; it should be changed to the following for node2:
```unless File.exist?(var_vm2_u01_disk) ``` 
If it works in your environment, I guess that is because you already have that ./standby_u01.vdi present.
Could you please try to perform a clean vagrant up command when you do not have the ./standby_u01.vdi on the filesystem?

**Comment by rcitton** [comment]
Yes , I started from scratch (on OL7.7, Vagrant 2.2.5, Vbox 6.0.12r133076) and as says everything went fine. Anyway yes the line 340 need to be addressed... Ill take care for it asap

**Comment by rcitton** [comment]
The change is done, waiting on merge to be complete

**Comment by rcitton** [comment]
the merge is done, please check

**Comment by mvelikikh** [comment]
I was able to create the virtual machines using the updated Vagrantfile. 
Thank you for fixing that.
I am closing this issue.
