### ISSUE TITLE
Add Support for Password Authentication to the OL 8 Box

### ISSUE THREAD

**Issue by fribeiro1** [oracle/vagrant-boxes#187]
The "config.ssh.password" property (https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-password) is currently ignored by the OL 8 box.

**Comment by scoter-oracle** [comment]
Hi, we use the ssh-key based authentication, as also suggested by Vagrant team on the webpage reported above.

**Comment by fribeiro1** [comment]
That's fine, thanks!
