### ISSUE TITLE
Getting clipboard error while using vagrant 2.26 with virtualbox 6.1.0

### ISSUE THREAD

**Issue by riksanyal** [oracle/vagrant-boxes#188]
I get this error after following the steps mentioned in #178 and using @scoter-oracle 's solution

```
A customization command failed:

["modifyvm", :id, "--clipboard", "bidirectional"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "37c87f70-98ed-4729-bc37-29338849a4e0", "--clipboard", "bidirectional"]

```
Does anyone know how to solve this?

**Comment by scoter-oracle** [comment]
Hi, this is a Vagrant issue and we already shared the same to the Vagrant team.
The syntax has changed from "--clipboard" to "--clipboard-mode" in VirtualBox 6.1.
While waiting for a fix from the Vagrant team you can use:

# VBoxManage modifyvm <vm-name> --clipboard-mode disabled|hosttoguest|guesttohost|bidirectional

**Comment by scoter-oracle** [comment]
BTW, you can open an other issue to the Vagrant Project.

**Comment by jpruiz114** [comment]
This is failing again under Vagrant 2.2.7 and Virtual Box 6.

A customization command failed:

["modifyvm", :id, "--clipboard-mode", "bidirectional"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "4a38a623-f3f1-4464-a423-39d48c758a97", "--clipboard-mode", "bidirectional"]

Stderr: Oracle VM VirtualBox Command Line Management Interface Version 6.0.16
(C) 2005-2020 Oracle Corporation
All rights reserved.

**Comment by scoter-oracle** [comment]
VirtualBox 6.1 introduced the "--clipboard-mode" difference from "--clipboard".
We already managed it on VirtualBox and next release for VirtualBox 6.1 will accept both options.

**Comment by scoter-oracle** [comment]
VirtualBox 6.1.4 accepts both "--clipboard-mode" and "--clipboard" so the issue should be fixed in any case.
