### ISSUE TITLE
vagrant up command fails during master step: [ERROR] Please allow iptables default FORWARD rule to ACCEPT

### ISSUE THREAD

**Issue by tomasz2048** [oracle/vagrant-boxes#193]
command run: vagrant up 
in Kubernetes folder
running with Virtualbox 6.0 on Windows 10

[...]  
  master: Installed:
    master:   iproute-tc.x86_64 0:4.16.0-1.0.5.el7     kubeadm.x86_64 0:1.12.7-1.2.3.el7
    master:   kubectl.x86_64 0:1.12.7-1.2.3.el7        kubelet.x86_64 0:1.12.7-1.2.3.el7
    master:
    master: Dependency Installed:
    master:   conntrack-tools.x86_64 0:1.4.4-5.el7_7.2
    master:   kubernetes-cni.x86_64 0:0.6.0-2.2.1.el7
    master:   kubernetes-cni-plugins.x86_64 0:0.7.5-1.0.1.el7
    master:   libnetfilter_cthelper.x86_64 0:1.0.0-10.el7_7.1
    master:   libnetfilter_cttimeout.x86_64 0:1.0.0-6.el7_7.1
    master:   libnetfilter_queue.x86_64 0:1.0.2-2.el7_2
    master:   socat.x86_64 0:1.7.3.2-2.el7
    master: Complete!
    master: net.bridge.bridge-nf-call-ip6tables = 1
    master: net.bridge.bridge-nf-call-iptables = 1
    master: Your Kubernetes VM is ready to use!
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: shell...
    master: Running: C:/Users/tomasz/AppData/Local/Temp/vagrant-shell20200112-15956-16puilw.sh
    master: /tmp/vagrant-shell: Setup Master node -- be patient!
    master: /tmp/vagrant-shell: kubeadm-setup.sh did not complete successfully
    master: Last lines of kubeadm-setup.log:
    master: Trying to pull repository container-registry.oracle.com/kubernetes/kube-proxy ...
    master: v1.12.7: Pulling from container-registry.oracle.com/kubernetes/kube-proxy
    master: Digest: sha256:f4f9e7b70a65f4f7d751da9b97c7536b21a7ac2b301155b0685778fc83d5510f
    master: Status: Image is up to date for container-registry.oracle.com/kubernetes/kube-proxy:v1.12.7
    master: container-registry.oracle.com/kubernetes/kube-proxy:v1.12.7
    master: Checking whether docker can run container ...
    master: Checking iptables default rule ...
    master: [ERROR] Please allow iptables default FORWARD rule to ACCEPT
    master:         the way to do it:
    master:         # /sbin/iptables -P FORWARD ACCEPT
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by AmedeeBulle** [comment]
The issue comes from the recently released docker 19.03 which resets the FORWARD policy...

Please note that this Vagrantfile is for Kubernetes 1.12 and earlier, for a more recent version you should use the OLCNE Vagrantfile from this repository.

If you really need to install Kubernetes 1.12, you can workaround the issue by using the previous docker version. 
If you are using the `vagrant-env` vagrant plugin add the following to your `.env` file
```
DOCKER_VERSION=18.09.8.ol
```
Alternatively you can edit the Vagrantfile directly:
```
-  DOCKER_VERSION = default_s('DOCKER_VERSION', '')
+  DOCKER_VERSION = default_s('DOCKER_VERSION', '18.09.8.ol')
```
