### ISSUE TITLE
Database boxes - Remove AND lists from install.sh scripts

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#196]
In #161, `set -e` was added to the `install.sh` scripts for the single instance database boxes in order to abort the installation on any error. However, the scripts don't necessarily abort after the actual failing command, because some commands are pipelined using AND (`&&`) lists. This complicates troubleshooting.

In the comments on #161, removing the AND lists was discussed. This would ensure that the scripts abort immediately after the failing command. @gvenzl indicated that he agreed with this approach.

So, I suggest modifying the `install.sh` scripts for the single instance database boxes to remove the AND lists. I've tested this for all of the boxes, and they all build and run correctly. If you'd like, I'd be happy to submit a PR for this.

**Comment by gvenzl** [comment]
Hi @PaulNeumann,

Yes, please submit a PR for this change. Thank you very, very much!

Thx,
