### ISSUE TITLE
DB box enhancement - Allow port configuration

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#198]
For the single-instance database boxes, it would be helpful if the listener and EM Express ports could be configured in the Vagrantfile, instead of having the default values hard coded. This would allow running multiple boxes (or multiple copies of the same box) at the same time. Also, some organizations require using a non-standard listener port, and this would allow these boxes to work the same way.

I've tested this, and it wouldn't be hard to implement. For the non-XE boxes:

* In the Vagrantfiles, create 2 new constants, LISTENER_PORT and EM_EXPRESS_PORT, and assign them the default values (which the user could override). Use these constants for port forwarding, and pass them to the `install.sh` scripts in the env section.
* Modify the `dbca.rsp.tmpl` files to use a placeholder for emExpressPort, instead of a hard coded value.
* Modify the `install.sh` scripts to:
  * Use $LISTENER_PORT instead of 1521 when creating listener.ora and tnsnames.ora.
  * Replace the emExpressPort placeholder in dbca.rsp with the value in $EM_EXPRESS_PORT.
  * Add 2 statements to the post DB setup tasks
    * `ALTER SYSTEM SET LOCAL_LISTENER = '(ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = $LISTENER_PORT))' SCOPE=BOTH;`
    * `ALTER SYSTEM REGISTER;`
* Update the `README.md` files to document the new functionality.

The XE boxes would be simpler. The 18c XE response file includes parameters for both listener port and EM Express port, and the 11g XE response file includes a parameter for listener port. EM Express doesn't apply to 11g XE.

(It's also possible to modify just the host ports in the Vagrantfile and forward them to the default ports in the guest. That would provide many of the same benefits, but then users would have to remember that the host and guest ports are different and use different connection parameters for host and guest tools, which isn't ideal.)

If you agree that this would be a worthwhile enhancement, I'd be happy to work on it.

(Slightly off topic: Whether this suggested enhancement is implemented or not, it might make sense to revisit #35. It'd be cleaner to have the option of configuring the boxes using `.env.local` or environment variables, instead of editing the Vagrantfiles. I'd also be happy to work on that, if you'd like.)

**Comment by PaulNeumann** [comment]
To hopefully save you some time when considering this, I've submitted a PR. Looking at the proposed changes might be easier than just reading a description of them. The PR lists the testing that's been done, and everything seems to be working as intended.

If you decide that this is a good idea, I'd be happy to make any changes you'd like.

**Comment by gvenzl** [comment]
Thanks a lot for your contribution, @PaulNeumann!
This is great!
