### ISSUE TITLE
ora-response file oracle database 19c vagrant Box (db_install.rsp.tmpl) 

### ISSUE THREAD

**Issue by delassiops** [oracle/vagrant-boxes#201]
Hi,

Just comparing the db_install.rsp.tmpl in ora-response directory with original db_install.rsp (LINUX.X64_193000_db_home\install\response) i just discover that those parameter are no more valid for responseFileVersion: rspfmt_dbinstall_response_schema_v19.0.0

SELECTED_LANGUAGES=en
SECURITY_UPDATES_VIA_MYORACLESUPPORT=false
DECLINE_SECURITY_UPDATES=true
oracle.installer.autoupdates.option=SKIP_UPDATES

also below have changing name from

oracle.install.db.DBA_GROUP=dba
oracle.install.db.BACKUPDBA_GROUP=dba
oracle.install.db.DGDBA_GROUP=dba
oracle.install.db.KMDBA_GROUP=dba

to 

oracle.install.db.OSDBA_GROUP=dba
oracle.install.db.OSBACKUPDBA_GROUP=dba
oracle.install.db.OSDGDBA_GROUP=dba
oracle.install.db.OSKMDBA_GROUP=dba

Please can you update the old response file for those change

Best Regards

**Comment by PaulNeumann** [comment]
@delassiops I think you're right.

The db_install.rsp.tmpl files for some of the other single-instance database boxes have similar issues. To address all removed and renamed parameters, I suggest the following changes:

**19.3.0 and 18.3.0 db_install.rsp.tmpl files**

- Remove the SELECTED_LANGUAGES, SECURITY_UPDATES_VIA_MYORACLESUPPORT, DECLINE_SECURITY_UPDATES, and oracle.installer.autoupdates.option parameters
- Rename the following parameters:

  - oracle.install.db.DBA_GROUP to oracle.install.db.**OS**DBA_GROUP
  - oracle.install.db.BACKUPDBA_GROUP to oracle.install.db.**OS**BACKUPDBA_GROUP
  - oracle.install.db.DGDBA_GROUP to oracle.install.db.**OS**DGDBA_GROUP
  - oracle.install.db.KMDBA_GROUP to oracle.install.db.**OS**KMDBA_GROUP

**12.2.0.1 db_install.rsp.tmpl file**

- Remove the SELECTED_LANGUAGES and oracle.installer.autoupdates.option parameters
- Rename the following parameters:

  - oracle.install.db.DBA_GROUP to oracle.install.db.**OS**DBA_GROUP
  - oracle.install.db.BACKUPDBA_GROUP to oracle.install.db.**OS**BACKUPDBA_GROUP
  - oracle.install.db.DGDBA_GROUP to oracle.install.db.**OS**DGDBA_GROUP
  - oracle.install.db.KMDBA_GROUP to oracle.install.db.**OS**KMDBA_GROUP

**12.1.0.2 db_install.rsp.tmpl file**

- Remove the oracle.installer.autoupdates.option parameter

I've tested these changes, and the boxes build fine with the modified response files.

@gvenzl If you agree that this is a legitimate issue, and that the proposed changes are correct, I'd be happy to submit a PR.

**Comment by PaulNeumann** [comment]
To hopefully save you some time, I've submitted a PR for this. I've tested the changes, and the updated response files seem to be working correctly.
