### ISSUE TITLE
ol5 box

### ISSUE THREAD

**Issue by julianobarbosa** [oracle/vagrant-boxes#206]
is possible download ol5 box ?

**Comment by PaulNeumann** [comment]
As far as I know, Oracle hasn't provided an OL5 box, but there are several OL5 boxes available through Vagrant's website at [https://app.vagrantup.com/boxes/search](https://app.vagrantup.com/boxes/search)--just search for "Oracle Linux 5" or "Oracle 5".

***I haven't used any of these boxes***, but in general boxes built by the Bento project seem to be pretty reliable. The Bento OL5 boxes are called "bento/oracle-5.11" (64-bit) and "bento/oracle-5.11-i386" (32-bit).

I hope this helps.

**Comment by Djelibeybi** [comment]
Keep in mind that Oracle Linux 5 ends extended support in June 2020 so you only have 3 months left of updates (if you're paying for extended support) before the product is no longer updated.
