### ISSUE TITLE
vagrant up failing with mismatched guest editions

### ISSUE THREAD

**Issue by donraikes** [oracle/vagrant-boxes#210]
I recently upgraded my virtualbox installation to version 6.1.4.1377 and my vagrant version to 2.2.7.  I installed the extpack associated with this version of virtualbox.

I then cloned the vagrant-boxes repository and tried to run vagrant up in the oraclelinux/7 folder.

All seems well until I am informed that the guest editions do not match and when vagrant/vbox try to upgrade the guest editions there is a failure which stops the provisioning of my vagrant box.

A partial log of the session follows:

Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

c:\>v:

V:\>cd 7

V:\7>vagrant up
getting Proxy Configuration from Host...
Bringing machine 'ol7-vagrant' up with 'virtualbox' provider...
==> ol7-vagrant: Importing base box 'ol7-latest'...
==> ol7-vagrant: Matching MAC address for NAT networking...
==> ol7-vagrant: Setting the name of the VM: ol7-vagrant
==> ol7-vagrant: Clearing any previously set network interfaces...
==> ol7-vagrant: Preparing network interfaces based on configuration...
    ol7-vagrant: Adapter 1: nat
==> ol7-vagrant: Forwarding ports...
    ol7-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> ol7-vagrant: Running 'pre-boot' VM customizations...
==> ol7-vagrant: Booting VM...
==> ol7-vagrant: Waiting for machine to boot. This may take a few minutes...
    ol7-vagrant: SSH address: 127.0.0.1:2222
    ol7-vagrant: SSH username: vagrant
    ol7-vagrant: SSH auth method: private key
    ol7-vagrant:
    ol7-vagrant: Vagrant insecure key detected. Vagrant will automatically replace
    ol7-vagrant: this with a newly generated keypair for better security.
    ol7-vagrant:
    ol7-vagrant: Inserting generated public key within guest...
    ol7-vagrant: Removing insecure key from the guest if it's present...
    ol7-vagrant: Key inserted! Disconnecting and reconnecting using new SSH key...
==> ol7-vagrant: Machine booted and ready!
==> ol7-vagrant: Configuring proxy environment variables...
==> ol7-vagrant: Configuring proxy for Yum...
[ol7-vagrant] GuestAdditions versions on your host (6.1.4) and guest (6.0.12) do not match.
...
Copy iso file D:\vbox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 6.1.4 - guest version is 6.0.12
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.1.4 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 6.0.12 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel
4.14.35-1902.5.2.2.el7uek.x86_64.
VirtualBox Guest Additions: Running kernel modules will not be replaced until
the system is restarted
An error occurred during installation of VirtualBox Guest Additions 6.1.4. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
Unmounting Virtualbox Guest Additions ISO from: /mnt
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.12
VBoxService inside the vm claims: 6.1.4
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.12
VBoxService inside the vm claims: 6.1.4
Going on, assuming VBoxService is correct...
==> ol7-vagrant: Checking for guest additions in VM...
    ol7-vagrant: The guest additions on this VM do not match the installed version of
    ol7-vagrant: VirtualBox! In most cases this is fine, but in rare cases it can
    ol7-vagrant: prevent things such as shared folders from working properly. If you see
    ol7-vagrant: shared folder errors, please make sure the guest additions within the
    ol7-vagrant: virtual machine match the version of VirtualBox you have installed on
    ol7-vagrant: your host and reload your VM.
    ol7-vagrant:
    ol7-vagrant: Guest Additions Version: 6.0.12
    ol7-vagrant: VirtualBox Version: 6.1
==> ol7-vagrant: Setting hostname...
==> ol7-vagrant: Mounting shared folders...
    ol7-vagrant: /vagrant => V:/7
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device

V:\7>
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

c:\>v:

V:\>cd 7

V:\7>vagrant up
getting Proxy Configuration from Host...
Bringing machine 'ol7-vagrant' up with 'virtualbox' provider...
==> ol7-vagrant: Importing base box 'ol7-latest'...
==> ol7-vagrant: Matching MAC address for NAT networking...
==> ol7-vagrant: Setting the name of the VM: ol7-vagrant
==> ol7-vagrant: Clearing any previously set network interfaces...
==> ol7-vagrant: Preparing network interfaces based on configuration...
    ol7-vagrant: Adapter 1: nat
==> ol7-vagrant: Forwarding ports...
    ol7-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> ol7-vagrant: Running 'pre-boot' VM customizations...
==> ol7-vagrant: Booting VM...
==> ol7-vagrant: Waiting for machine to boot. This may take a few minutes...
    ol7-vagrant: SSH address: 127.0.0.1:2222
    ol7-vagrant: SSH username: vagrant
    ol7-vagrant: SSH auth method: private key
    ol7-vagrant:
    ol7-vagrant: Vagrant insecure key detected. Vagrant will automatically replace
    ol7-vagrant: this with a newly generated keypair for better security.
    ol7-vagrant:
    ol7-vagrant: Inserting generated public key within guest...
    ol7-vagrant: Removing insecure key from the guest if it's present...
    ol7-vagrant: Key inserted! Disconnecting and reconnecting using new SSH key...
==> ol7-vagrant: Machine booted and ready!
==> ol7-vagrant: Configuring proxy environment variables...
==> ol7-vagrant: Configuring proxy for Yum...
[ol7-vagrant] GuestAdditions versions on your host (6.1.4) and guest (6.0.12) do not match.
...
Copy iso file D:\vbox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 6.1.4 - guest version is 6.0.12
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.1.4 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 6.0.12 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel
4.14.35-1902.5.2.2.el7uek.x86_64.
VirtualBox Guest Additions: Running kernel modules will not be replaced until
the system is restarted
An error occurred during installation of VirtualBox Guest Additions 6.1.4. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start vboxadd.service
Redirecting to /bin/systemctl start vboxadd-service.service
Unmounting Virtualbox Guest Additions ISO from: /mnt
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.12
VBoxService inside the vm claims: 6.1.4
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.12
VBoxService inside the vm claims: 6.1.4
Going on, assuming VBoxService is correct...
==> ol7-vagrant: Checking for guest additions in VM...
    ol7-vagrant: The guest additions on this VM do not match the installed version of
    ol7-vagrant: VirtualBox! In most cases this is fine, but in rare cases it can
    ol7-vagrant: prevent things such as shared folders from working properly. If you see
    ol7-vagrant: shared folder errors, please make sure the guest additions within the
    ol7-vagrant: virtual machine match the version of VirtualBox you have installed on
    ol7-vagrant: your host and reload your VM.
    ol7-vagrant:
    ol7-vagrant: Guest Additions Version: 6.0.12
    ol7-vagrant: VirtualBox Version: 6.1
==> ol7-vagrant: Setting hostname...
==> ol7-vagrant: Mounting shared folders...
    ol7-vagrant: /vagrant => V:/7
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device

V:\7>

**Comment by AmedeeBulle** [comment]
Can you please also update your ol7 box?

We have recently released new boxes that should fix this issue.

```
vagrant box remove ol7-latest
vagrant up
```

**Comment by donraikes** [comment]
I removed the vagrant box as you suggested and when I ran vagrant up I got the message that the guest editions were mismatched but that they had been updated so I ran

 

Vagrant halt

 

Vagrant up

 

This time thte shared folders were mounted successfully and the provisioning is proceeding.

 

Thank you!

 

-- 
Thanks, Donald 

Quote of The Week: “Everyone is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid” –Albert Einstein

 

“As a leader, to be successful, is to help the people around you to be successful.” – Kent Boucher

 

Accessibility, like security, is better when built-in from the beginning rather than bolted on at the end.


http://www.oracle.com/
Donald Raikes | Accessibility Specialist
Mobile: HYPERLINK "tel:+15202717608"+15202717608 | VOIP: HYPERLINK "tel:+15205744033"+15205744033 
Oracle Accessibility Program Office
| Tucson, Arizona 

http://www.oracle.com/commitment

Oracle is committed to developing practices and products that help protect the environment
