### ISSUE TITLE
OLCNE: network creation failure

### ISSUE THREAD

**Issue by donraikes** [oracle/vagrant-boxes#212]
Hello,
I am attempting to learn about olcne by using the vagrant box configuration provided in this repository.

When I do a vagrant up, everything seems to be working fine until virtualbox tries to create the host-only network.  I get a couple of user control notifications on windows 10 which I respond yes to to allow virtualbox to make changes to my system, but the vagrant up process fails with the following message:

==> worker1: Clearing any previously set forwarded ports...
==> worker1: Clearing any previously set network interfaces...
==> worker1: Preparing network interfaces based on configuration...
    worker1: Adapter 1: nat
    worker1: Adapter 2: hostonly
==> worker1: Forwarding ports...
    worker1: 22 (guest) => 2222 (host) (adapter 1)
==> worker1: Running 'pre-boot' VM customizations...
==> worker1: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "2e5034c7-7fcc-487a-826a-f6623e261622", "--type", "headless"]

Stderr: VBoxManage.EXE: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.EXE: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.EXE: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

==> worker1: Clearing any previously set forwarded ports...
==> worker1: Clearing any previously set network interfaces...
==> worker1: Preparing network interfaces based on configuration...
    worker1: Adapter 1: nat
    worker1: Adapter 2: hostonly
==> worker1: Forwarding ports...
    worker1: 22 (guest) => 2222 (host) (adapter 1)
==> worker1: Running 'pre-boot' VM customizations...
==> worker1: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "2e5034c7-7fcc-487a-826a-f6623e261622", "--type", "headless"]

Stderr: VBoxManage.EXE: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.EXE: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.EXE: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

I am running virtualbox 6.1.4 and vagrant 2.2.7.

Any help would be appreciated.

**Comment by AmedeeBulle** [comment]
Hi,

This is related to the way Windows manages its network interfaces. I believe you might have changed your network settings in the past or you have particular security policies in place on your system.

I would suggest to look at this [VirtualBox forum post](https://forums.virtualbox.org/viewtopic.php?f=6&t=94277) and/or this [VirtualBox ticket](https://www.virtualbox.org/ticket/14832) to see if this solves your issue.

Thanks

**Comment by donraikes** [comment]
After reading the two refferenced links, I used the virtualbox gui to drop and recreate the host-only networks, and then running vagrant up in the olcne folder worked.
