### ISSUE TITLE
olcnectl module install --environment-name olcne-env --name olcne-cluster failing

### ISSUE THREAD

**Issue by donraikes** [oracle/vagrant-boxes#213]
I have been working through getting my olcne vagrant  cluster setup.
I fixed the networking problem, and had to rerun the vagrant up a number of times since each time a new machine is created it has to install the guest editions which requires a reboot so vagrant halt && vagrant up.

Finally all three vms were created master1, worker1 and worker2.

However at the end of the provisioning of master1 I get the following error:

    master1: ===== Create the Kubernetes module for olcne-env  =====
    master1: ===== Validate all required prerequisites are met for the Kubernetes module =====
    master1: ===== Deploy the Kubernetes module into olcne-env (Be patient!) =====
    master1: olcnectl module install --environment-name olcne-env --name olcne-cluster
    master1: Returned a non-zero code: 1
    master1: Last output lines:
    master1: To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
    master1: Here is one example how you may list all Kubernetes containers running in docker:
    master1:    - 'docker ps -a | grep kube | grep -v pause'
    master1:    Once you have found the failing container, you can inspect its logs with:
    master1:    - 'docker logs CONTAINERID'
    master1: See /var/tmp/cmd_AhVs1.log for details
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

How do I fix this problem?

**Comment by Djelibeybi** [comment]
Can you post the content of `/var/tmp/cmd_AhVs1.log` from your Master node?

**Comment by donraikes** [comment]
After examining /var/tmp/cmdAhVs1.log, it looks like I have run into proxy issues.  I need to update my nno_proxy settings in order for this to work.

 

I can post the log but I would have to redact the http_proxy values for security reasons.

-- 
Thanks, Donald 

“As a leader, to be successful, is to help the people around you to be successful.” – Kent Boucher

 

Accessibility, like security, is better when built-in from the beginning rather than bolted on at the end.


http://www.oracle.com/
Donald Raikes | Accessibility Specialist
Mobile: HYPERLINK "tel:+15202717608"+15202717608 | VOIP: HYPERLINK "tel:+15205744033"+15205744033 
Oracle Accessibility Program Office
| Tucson, Arizona 

http://www.oracle.com/commitment

Oracle is committed to developing practices and products that help protect the environment

**Comment by Djelibeybi** [comment]
Yeah, that sounds reasonable. If you have any issues changing your proxy settings, come and find me on Slack and I can point you towards suitable channels, etc. :)

**Comment by donraikes** [comment]
I think I am getting closer.

 

This time I got this failure:

 

    master1: ===== Generate and deploy X.509 Certificates =====

    master1: bash -e /etc/olcne/pki/olcne-tranfer-certs.sh

    master1: Returned a non-zero code: 255

    master1: Last output lines:

    master1: [INFO] Copying certificate files to: '192.168.99.101' as: 'vagrant'

    master1: [INFO] Copying certificate files to: '192.168.99.111' as: 'vagrant'

    master1: See /var/tmp/cmd_tIPUU.log for details

The SSH command responded with a non-zero exit status. Vagrant

assumes that this means the command failed. The output for this command

should be in the log above. Please read the output to determine what

went wrong.

 

 

--- contents of /var/tmp/cmd_tIPUU.log ---

[INFO] Copying certificate files to: '192.168.99.101' as: 'vagrant'

[INFO] Copying certificate files to: '192.168.99.111' as: 'vagrant'

-- end of /var/tmp/cmd_tIPUU.log ----

 

 

 

-- 
Thanks, Donald 

“As a leader, to be successful, is to help the people around you to be successful.” – Kent Boucher

 

Accessibility, like security, is better when built-in from the beginning rather than bolted on at the end.


http://www.oracle.com/
Donald Raikes | Accessibility Specialist
Mobile: HYPERLINK "tel:+15202717608"+15202717608 | VOIP: HYPERLINK "tel:+15205744033"+15205744033 
Oracle Accessibility Program Office
| Tucson, Arizona 

http://www.oracle.com/commitment

Oracle is committed to developing practices and products that help protect the environment

**Comment by donraikes** [comment]
Avi,

 

I tried pinging from master1 to worker1 and it worked fine, but when I tried to ssh from master1 to worker1 the connection was refused so that is why copying the certs failed I suspect.

 

-- 
Thanks, Donald 

“As a leader, to be successful, is to help the people around you to be successful.” – Kent Boucher

 

Accessibility, like security, is better when built-in from the beginning rather than bolted on at the end.


http://www.oracle.com/
Donald Raikes | Accessibility Specialist
Mobile: HYPERLINK "tel:+15202717608"+15202717608 | VOIP: HYPERLINK "tel:+15205744033"+15205744033 
Oracle Accessibility Program Office
| Tucson, Arizona 

http://www.oracle.com/commitment

Oracle is committed to developing practices and products that help protect the environment

**Comment by Djelibeybi** [comment]
> Avi,   I tried pinging from master1 to worker1 and it worked fine, but when I tried to ssh from master1 to worker1 the connection was refused so that is why copying the certs failed I suspect.  

I'll need to leave this to others to continue triaging, because this is outside my scope of knowledge now.

**Comment by donraikes** [comment]
After running vagrant destroy and fixing the proxy settings -- correctly this time, I reran vagrant up and all went well the olcne is up and operational.
