### ISSUE TITLE
APEX box - Update apex.sh script to support APEX 20.1

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#223]
APEX 20.1 has been released. The `apex.sh` script for the APEX box doesn't find the APEX 20.1 installer zip file, because it looks for files matching `apex_1*.*.zip`.

Changing line 32 of `apex.sh` from

```shell
APEX_INSTALL=`ls /vagrant/apex_1*.*.zip |tail -1`
```

to

```shell
APEX_INSTALL=$(find /vagrant -name "apex_*.*.zip" | tail -1)
```

allows the script to work with APEX 20.1 and above, as well as earlier versions. It also eliminates two ShellCheck warnings (SC2006 about using backtick notation and SC2012 about using ls instead of find).

I've verified that the box builds and runs correctly with this change. If you agree that this is a legitimate issue, and that the suggested approach is correct, I'd be happy to submit a PR.

**Comment by AmedeeBulle** [comment]
Sure go ahead with a PR, but consider using the `-maxdepth`  `find` option to avoid unnecessary crawling in the `/vagrant` tree...

**Comment by PaulNeumann** [comment]
Thanks! I appreciate your suggestions. I've incorporated them, and I've also added the `-type f` `find` test to limit the search to regular files. I'll submit a PR as soon as I finish testing.
