### ISSUE TITLE
OLCNE - Istio module fails to install

### ISSUE THREAD

**Issue by rafabene** [oracle/vagrant-boxes#226]
If Istio module is enable, the following error is presented when creating the module:

` Error: unable to build kubernetes objects from release manifest: [unable to recognize “”: no matches for kind “DestinationRule” in version “networking.istio.io/v1alpha3”, unable to recognize “”: no matches for kind “attributemanifest” in version “config.istio.io/v1alpha2”, unable to recognize “”: no matches for kind “handler” in version “config.istio.io/v1alpha2”, unable to recognize “”: no matches for kind “instance” in version “config.istio.io/v1alpha2”, unable to recognize “”: no matches for kind “rule” in version “config.istio.io/v1alpha2”]”`

**Comment by Djelibeybi** [comment]
Fixed by #228
