### ISSUE TITLE
OLCNE - olcnectl module validate recommends a wrong command

### ISSUE THREAD

**Issue by rafabene** [oracle/vagrant-boxes#227]
Script to validate executes:  **olcnectl module validate --environment-name olcne-env --name olcne-cluster** but it returns the following error

> Please execute the following operations on 192.168.99.111:8090
  podman image pull --apiserver-advertise-address/pause:3.1

But when I execute the command **podman image pull --apiserver-advertise-address/pause:3.1** it replies:
> Error: unknown flag: --apiserver-advertise-address/pause:3.1

**Comment by Djelibeybi** [comment]
Fixed bv #228
