### ISSUE TITLE
APEX box - ORDS download URL in README outdated

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#234]
The ORDS download URL in the `README.md` file for the APEX box redirects to the download page for ORDS 19.2. The download URL for the current version (19.4) is [https://www.oracle.com/database/technologies/appdev/rest-data-services-downloads.html](https://www.oracle.com/database/technologies/appdev/rest-data-services-downloads.html). I suggest updating the URL in the `README.md` file.

If you agree that this is a legitimate issue, and that the proposed URL is correct, I'd be happy to submit a PR.

**Comment by scoter-oracle** [comment]
Paul, thanks for reporting this; it should be great if you can submit a PR. Thanks
