### ISSUE TITLE
Vagrant Boxes not working when Hyper-V is enabled (Yum fails to download packages)

### ISSUE THREAD

**Issue by sh4nnongoh** [oracle/vagrant-boxes#240]
Hi, referencing the following issue:
https://github.com/oracle/vagrant-boxes/issues/222

Is there a way to make the Oracle vagrant boxes work without disabling Hyper-V on Windows platform? I am using Docker for Windows as well, which requires Hyper-V enabled.

I am trying to spin up a local Oracle Database XE, but it seems that both Docker and Vagrant solutions are not working on the Windows platform.

**Comment by sh4nnongoh** [comment]
Pasting logs below for completeness.

Versions:
- Vagrant 2.2.9
- VirtualBox 6.1.6

`
getting Proxy Configuration from Host...
Bringing machine 'oracle18c-xe-vagrant' up with 'virtualbox' provider...
==> oracle18c-xe-vagrant: Importing base box 'oraclelinux/7'...
==> oracle18c-xe-vagrant: Matching MAC address for NAT networking...
==> oracle18c-xe-vagrant: Checking if box 'oraclelinux/7' version '7.8.128' is up to date...
==> oracle18c-xe-vagrant: Setting the name of the VM: oracle18c-xe-vagrant
==> oracle18c-xe-vagrant: Clearing any previously set network interfaces...
==> oracle18c-xe-vagrant: Preparing network interfaces based on configuration...
    oracle18c-xe-vagrant: Adapter 1: nat
==> oracle18c-xe-vagrant: Forwarding ports...
    oracle18c-xe-vagrant: 1521 (guest) => 1521 (host) (adapter 1)
    oracle18c-xe-vagrant: 5500 (guest) => 5500 (host) (adapter 1)
    oracle18c-xe-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> oracle18c-xe-vagrant: Running 'pre-boot' VM customizations...
==> oracle18c-xe-vagrant: Booting VM...
==> oracle18c-xe-vagrant: Waiting for machine to boot. This may take a few minutes...
    oracle18c-xe-vagrant: SSH address: 127.0.0.1:2222
    oracle18c-xe-vagrant: SSH username: vagrant
    oracle18c-xe-vagrant: SSH auth method: private key
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant: Vagrant insecure key detected. Vagrant will automatically replace
    oracle18c-xe-vagrant: this with a newly generated keypair for better security.
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant: Inserting generated public key within guest...
    oracle18c-xe-vagrant: Removing insecure key from the guest if it's present...
    oracle18c-xe-vagrant: Key inserted! Disconnecting and reconnecting using new SSH key...
==> oracle18c-xe-vagrant: Machine booted and ready!
==> oracle18c-xe-vagrant: Checking for guest additions in VM...
==> oracle18c-xe-vagrant: Setting hostname...
==> oracle18c-xe-vagrant: Configuring proxy environment variables...
==> oracle18c-xe-vagrant: Configuring proxy for Yum...
==> oracle18c-xe-vagrant: Mounting shared folders...
    oracle18c-xe-vagrant: /vagrant => C:/Users/sh4nn/Documents/oracledb/vagrant-boxes/OracleDatabase/18.4.0-XE
==> oracle18c-xe-vagrant: Running provisioner: shell...
    oracle18c-xe-vagrant: Running: C:/Users/sh4nn/AppData/Local/Temp/vagrant-shell20200508-8200-1obnd3l.sh
    oracle18c-xe-vagrant: INSTALLER: Started up
    oracle18c-xe-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/developer/x86_64/repodata/0bd92e7b70801385004639b2572fa5acbb296105-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle18c-xe-vagrant: Trying other mirror.
    oracle18c-xe-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/3c9e929f785ebe41da578ecb9bd8cd0bb1bedda5-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle18c-xe-vagrant: Trying other mirror.
    oracle18c-xe-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/repodata/efd121f50994397cff54ee66360cfe7c918c07dd-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle18c-xe-vagrant: Trying other mirror.
    oracle18c-xe-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/repodata/efd121f50994397cff54ee66360cfe7c918c07dd-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle18c-xe-vagrant: Trying other mirror.
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant:  One of the configured repositories failed (Unknown),
    oracle18c-xe-vagrant:  and yum doesn't have enough cached data to continue. At this point the only
    oracle18c-xe-vagrant:  safe thing yum can do is fail. There are a few ways to work "fix" this:
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant:      1. Contact the upstream for the repository and get them to fix the problem.
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant:      2. Reconfigure the baseurl/etc. for the repository, to point to a working
    oracle18c-xe-vagrant:         upstream. This is most often useful if you are using a newer
    oracle18c-xe-vagrant:         distribution release than is supported by the repository (and the
    oracle18c-xe-vagrant:         packages for the previous distribution release still work).
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant:      3. Run the command with the repository temporarily disabled
    oracle18c-xe-vagrant:             yum --disablerepo=<repoid> ...
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant:      4. Disable the repository permanently, so yum won't use it by default. Yum
    oracle18c-xe-vagrant:         will then just ignore the repository until you permanently enable it
    oracle18c-xe-vagrant:         again or use --enablerepo for temporary usage:
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant:             yum-config-manager --disable <repoid>
    oracle18c-xe-vagrant:         or
    oracle18c-xe-vagrant:             subscription-manager repos --disable=<repoid>
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant:      5. Configure the failing repository to be skipped, if it is unavailable.
    oracle18c-xe-vagrant:         Note that yum will try to contact the repo. when it runs most commands,
    oracle18c-xe-vagrant:         so will have to try and fail each time (and thus. yum will be be much
    oracle18c-xe-vagrant:         slower). If it is a very temporary problem though, this is often a nice
    oracle18c-xe-vagrant:         compromise:
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant:             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
    oracle18c-xe-vagrant:
    oracle18c-xe-vagrant: ol7_developer_EPEL: Check uncompressed DB failed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
`

**Comment by PaulNeumann** [comment]
@sh4nnongoh As far as I know, there's not a way to get the boxes to work on Windows hosts without disabling Hyper-V. Hyper-V support in VirtualBox is an experimental feature (see [this section](https://www.virtualbox.org/manual/UserManual.html#hyperv-support) of the VirtualBox user manual), so some issues are to be expected. One workaround is to run Docker in a Linux VM (like the [DockerEngine box](https://github.com/oracle/vagrant-boxes/tree/master/DockerEngine) in this repository), rather than on the Windows host.

**Comment by AmedeeBulle** [comment]
@sh4nnongoh, as @PaulNeumann is pointing out, there isn't anything we can do at Vagrant level as it boils down to a VirtualBox/Hyper-V compatibility issue.

Oracle is working on a better integration of VirtualBox on Hyper-V, but for the time being it remains experimental.

As Paul is suggesting, if you need to run both Docker and VirtualBox/Vagrant at the same time, your only option is to disable Hyper-V and run Docker in a VirtualBox Linux VM.

**Comment by sh4nnongoh** [comment]
Alright, thanks for the response @AmedeeBulle @PaulNeumann . Is it possible to update the README to reflect this? So that future explorers can save some time.

**Comment by scoter-oracle** [comment]
This is not something related to our Vagrant boxes, or generally to Vagrant. Once Hyper-V is enabled on a Ms-windows system, the same gets&locks the CPU virtualization features and those cannot be used by other hypervisors (like VirtualBox).
