### ISSUE TITLE
sqlplus: command not found in an OracleRAC environment

### ISSUE THREAD

**Issue by LarissaAuberger** [oracle/vagrant-boxes#248]
Hi,
I installed an OracleRAC environment following these instructions:
https://github.com/oracle/vagrant-boxes/tree/master/OracleRAC

After `vigrant up` I see two notes running.
Now I am trying to connect to database (Step 5 Connect to the database).

I do
`vagrant ssh node1` 
`sudo su - oracle`
All works fine so far.

`echo $ORACLE_HOME`
/u01/app/oracle/product/19.3.0.0/dbhome_1

`echo $ORACLE_SID`
DB193H12

However,
`sqlplus / as sysdba` 
shows
`-bash: sqlplus: command not found`

What's wrong? 
Thank you!

**Comment by LarissaAuberger** [comment]
Fixed this by setting 
`export ORACLE_HOME=/u01/app/19.3.0.0/grid`

**Comment by Djelibeybi** [comment]
You probably need to set the environment by running `. oraenv` once you've changed to the `oracle` user.

**Comment by LarissaAuberger** [comment]
Thanks!
When running . oraenv - where do I get the correct values for ORACLE_HOME , ORACLE_BASE?
(I am a first-time Vagrant/OracleRAC user)...

Is there any doc that describes `Step 5 Connect to the database` in more detail?

**Comment by Djelibeybi** [comment]
Good question. As per your original comment, `ORACLE_HOME` and `ORACLE_BASE` should already be set. I'll assign this to the DB folks so they can answer, but keep in mind it's Memorial Day weekend in the USA, so they may not reply until tomorrow.

**Comment by LarissaAuberger** [comment]
yes, they are set, but I would expect 
`ORACLE_HOME`
to point to something like `/u01/app/19.3.0.0/grid/bin` in a RAC environment, as `/u01/app/oracle/product/19.3.0.0/dbhome_1` is empty in my environment.

Thanks for assigning this so quickly!

**Comment by rcitton** [comment]
Hi Larissa, Ive fixed this in the next update. Oracle env setting was overwrite grid env setting

**Comment by LarissaAuberger** [comment]
Can I fix this manually on my environment now?

**Comment by rcitton** [comment]
sure it's really simple.
Connected as 'grid' user you should just add following rows under .bash_profile (and remove the wrong one)

#node1
export ORACLE_HOME=/u01/app/19.3.0.0/grid/bin
export PATH=$ORACLE_HOME/bin:$PATH
export ORACLE_SID=+ASM1

#node2
export ORACLE_HOME=/u01/app/19.3.0.0/grid/bin
export PATH=$ORACLE_HOME/bin:$PATH
export ORACLE_SID=+ASM2

**Comment by LarissaAuberger** [comment]
thanks, @rcitton - closing this.
