### ISSUE TITLE
Failed to start oracle DB in an OracleRAC env

### ISSUE THREAD

**Issue by LarissaAuberger** [oracle/vagrant-boxes#249]
After fixing env variables following https://github.com/oracle/vagrant-boxes/issues/248, 
I am facing issues with starting the database.

Followed these instructions to setup vagrant, virtualBox and OracleRAC:
https://github.com/oracle/vagrant-boxes/tree/master/OracleRAC

 `sudo su - grid`

`[grid@ol7-rac-node2 ~]$ echo $ORACLE_HOME`
`/u01/app/19.3.0.0/grid`

`[grid@ol7-rac-node2 ~]$ echo $ORACLE_BASE`
`  `

`[grid@ol7-rac-node2 ~]$ echo $ORACLE_SID`
`+ASM2`

`[grid@ol7-rac-node2 ~]$ echo $GRID_HOME`
`  `

```
[grid@ol7-rac-node2 ~]$ sqlplus / as sysdba

SQL*Plus: Release 19.0.0.0.0 - Production on Mon May 25 02:04:41 2020
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to an idle instance.

SQL>startup
ORA-01078: failure in processing system parameters
ORA-29701: unable to connect to Cluster Synchronization Service
SQL>
```

Any recommendation on what's wrong?

**Comment by LarissaAuberger** [comment]
Tried to manually start ASM:

```
[grid@ol7-rac-node2 bin]$ crsctl.bin start resource -all
crsctl.bin: error while loading shared libraries: libhasgen19.so: cannot open shared object file: No such file or directory
```

Library is in `$ORACLE_HOME/lib/libhasgen19.so`

Need to set
`export LD_LIBRARY_PATH=$ORACLE_HOME/lib`

**Comment by LarissaAuberger** [comment]
Starting ASM manually still fails:

```
[grid@ol7-rac-node2 19.3.0.0]$ crsctl.bin start resource -all
Oracle Clusterware infrastructure error in CRSCTL (OS PID 23042): ADR home path /u01/app/grid/diag/crs/ol7-rac-node2/crs does not exist; ADR initialization will try to create it
CRS-4047: No Oracle Clusterware components configured.
CRS-4000: Command Start failed, or completed with errors.
```

**Comment by rcitton** [comment]
Hi Larissa, did you deploy on a Ms Windows, Mac-OSX or linux? Are you sure the deploy went fine w/o errors? do you have the output of "vagrant up" command? In case you want redeploy: "vagrant destroy -f" and then "vagrant up". Check carefully the spool of "vagrant up" command as im quite sure you are getting errors on make the setup.

**Comment by LarissaAuberger** [comment]
My host is Windows 2016 server.
I will re-run vagrant up and capture the output. Thanks!

**Comment by rcitton** [comment]
Larissa, just a note as this may happens on Ms Windows.
If you move the OracleRAC content (as the others) using ftp, windows may add "\r" at the end of the scripts and this is a problem during the deployment. So be sure you are getting the zip (as clone) on such server and that you uncompress it directly on such host. Let me know

**Comment by LarissaAuberger** [comment]
@rcitton , I re-ran `vigrant up` after getting the zip as clone, as you suggested.
output looks good for `node2`, but failed for `node1` while inserting generated public key:

[output.txt](https://github.com/oracle/vagrant-boxes/files/4676982/output.txt)

Command line shows: 
```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

There is no `config.vm.boot_timeout` property in the Vagrantfile. Any other hints?

Is there an option to re-run this without the need to setup node2, as it is obviously good?

Thank you!

**Comment by rcitton** [comment]
Hi Larissa, 
you can cleanup what done so far for node1 issuing: "vagrant destroy node1"
then you can re-try the deploy for node1 issuing: "vagrant up node1".
Node2 will be untouch and keep :)

**Comment by LarissaAuberger** [comment]
Where would I find `config.vm.boot_timeout` (in case the issue is with the timeout?)

**Comment by totalamateurhour** [comment]
You should be able to add this property yourself, per the documentation:

https://www.vagrantup.com/docs/vagrantfile/machine_settings.html

**Comment by rcitton** [comment]
Larissa, if you need config.vm.boot_timeout your host maybe it's to much overloaded... :)

**Comment by LarissaAuberger** [comment]
@rcitton , you need to fix the default - `config.vm.boot_timeout = 400` made it work ;-)

**Comment by LarissaAuberger** [comment]
@rcitton during the node1 configuration I see this
```
    node1: Launching Oracle Grid Infrastructure Setup Wizard...
    node1: [FATAL] [INS-32603] The central inventory was not detected.
    node1:    ACTION: The -executeConfigTools flag can only be used for an Oracle home software that has been already installed using the configure or upgrade options. Ensure that the orainstRoot.sh script, from the inventory location, has been executed.
```

and this 
```
 node1: /vagrant_scripts/12_Make_ASMLib_RECO/grid/bin/sqlplus: Permission denied
```

Any steps I have missed prior to the deployment?

**Comment by rcitton** [comment]
Larissa, if it was working for node2 , it should works for node1 too. :)
Do you have possibility to share the vagrant up output ? if the attachment is an issue here, You can reach me at ruggero.citton@oracle.com

**Comment by LarissaAuberger** [comment]
@rcitton , thanks for all your support.
Output from node2 is in comment https://github.com/oracle/vagrant-boxes/issues/249#issuecomment-633528995
It does not have the "Launching Oracle Grid Infrastructure" part that reports an issue for node1.

node1 is still being deployed on my overloaded machine ;-)

**Comment by LarissaAuberger** [comment]
@rcitton , thank you so much for your support. Closing the defect, as OracleRAC deployment was successful.
