### ISSUE TITLE
Network between pods not working

### ISSUE THREAD

**Issue by gvenzl** [oracle/vagrant-boxes#38]
Reposting this from a blog post comment:

Hi Gerald,
Thank you for this guide. I followed this guide and installed 3 nodes k8s cluster. However I found there is something wrong with network between pods

[vagrant@master vagrant]$ kubectl get po -o wide -n kube-system
NAME READY STATUS RESTARTS AGE IP NODE
etcd-master.vagrant.vm 1/1 Running 3 2d 192.168.99.100 master.vagrant.vm
kube-apiserver-master.vagrant.vm 1/1 Running 7 2d 192.168.99.100 master.vagrant.vm
kube-controller-manager-master.vagrant.vm 1/1 Running 3 2d 192.168.99.100 master.vagrant.vm
kube-dns-855949bbf-d4cj2 3/3 Running 6 2d 10.244.0.6 master.vagrant.vm
kube-flannel-ds-cmq2z 1/1 Running 1 2d 192.168.99.101 worker1.vagrant.vm
kube-flannel-ds-h87pm 1/1 Running 3 2d 192.168.99.100 master.vagrant.vm
kube-flannel-ds-ssdcw 1/1 Running 1 2d 192.168.99.102 worker2.vagrant.vm
kube-proxy-c97rv 1/1 Running 2 2d 192.168.99.100 master.vagrant.vm
kube-proxy-fd9c8 1/1 Running 1 2d 192.168.99.102 worker2.vagrant.vm
kube-proxy-w5ggl 1/1 Running 1 2d 192.168.99.101 worker1.vagrant.vm
kube-scheduler-master.vagrant.vm 1/1 Running 3 2d 192.168.99.100 master.vagrant.vm
kubernetes-dashboard-7c966ddf6d-dzwf7 1/1 Running 3 2d 10.244.0.7 master.vagrant.vm
tiller-deploy-75f5797b-5ps8s 1/1 Running 0 46m 10.244.1.2 worker1.vagrant.vm
[vagrant@master vagrant]$ ping 10.244.1.2
PING 10.244.1.2 (10.244.1.2) 56(84) bytes of data.
^C
— 10.244.1.2 ping statistics —
56 packets transmitted, 0 received, 100% packet loss, time 55097ms

Did you encounter this issue?

Thanks,
Junyi.

**Comment by AmedeeBulle** [comment]
This is should not happen:
```
vagrant@master ~]$ kubectl get pods -n kube-system -o wide | grep tiller
tiller-deploy-75f5797b-8pmb9                1/1       Running   0          2h        10.244.2.15      worker2.vagrant.vm
[vagrant@master ~]$ ping -c 3 10.244.2.15
PING 10.244.2.15 (10.244.2.15) 56(84) bytes of data.
64 bytes from 10.244.2.15: icmp_seq=1 ttl=63 time=0.461 ms
64 bytes from 10.244.2.15: icmp_seq=2 ttl=63 time=0.528 ms
64 bytes from 10.244.2.15: icmp_seq=3 ttl=63 time=0.444 ms

--- 10.244.2.15 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.444/0.477/0.528/0.044 ms
```
- Ensure you have the latest scripts -- we have some network issues fixed with https://github.com/oracle/vagrant-boxes/pull/22 
- Was the cluster restarted? we have seen some routing issues after rebooting all boxes
- Which Docker version is installed (17.06 or 17.12)?

On a side note, Helm won't run "out of the box" as the cluster does not have any Persistent Volumes configured...

**Comment by AmedeeBulle** [comment]
Closing, we can re-open as needed
