### ISSUE TITLE
Database 11.2.0.2 box should use template for xe.rsp

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#42]
The `install.sh` script for the Oracle Database 11.2.0.2 box modifies the `ORACLE_PASSWORD` and `ORACLE_CONFIRM_PASSWORD` values in the `xe.rsp` file with the generated Oracle password (or the password set in the `ORACLE_PWD` envrionment variable, if applicable).  This causes two problems:

- After the first `vagrant up`, git treats the `xe.rsp` file as modified.
- It's more difficult to start over after a `vagrant destroy`.  Unless `xe.rsp` is edited to change the `ORACLE_PASSWORD` and `ORACLE_CONFIRM_PASSWORD` values back to "`###ORACLE_PWD###`", subsequent `vagrant up` operations will use the password generated the first time `vagrant up` was run.  This happens because the string "`###ORACLE_PWD###`" no longer exists in `xe.rsp`, so `sed` can't replace it with the new password).

One solution is to use a template for `xe.rsp`.  This is how response files are handled for the Oracle Database 12.2.0.1 box.  The following changes would fix the issue:

- Rename the existing `xe.rsp` file to `xe.rsp.tmpl`.
- Add one line of code to `install.sh` to copy `xe.rsp.tmpl` to `xe.rsp` before replacing the "`###ORACLE_PWD###`" strings with the generated password.
- Add one line of code to `install.sh` to delete `xe.rsp` after the database is created.

**Comment by PaulNeumann** [comment]
If you agree that this is a legitimate issue, and that the suggested changes are the right way to address it, I'd be happy to submit a pull request.

**Comment by PaulNeumann** [comment]
To (hopefully) save you some time, I've submitted a pull request for this.  Handling the response file the same way as the Oracle Database 12.2.0.1 box fixes the issue, and it's a straightforward change.

**Comment by gvenzl** [comment]
Merged!
