### ISSUE TITLE
Can't open the official website 

### ISSUE THREAD

**Issue by vinkdong** [oracle/vagrant-boxes#43]
![image](https://user-images.githubusercontent.com/10599904/41215618-be5d3060-6d83-11e8-93f4-b735dd9ba94c.png)

![image](https://user-images.githubusercontent.com/10599904/41215638-e0aaa274-6d83-11e8-94ce-ab2a3025394d.png)

**Comment by AmedeeBulle** [comment]
There was indeed an issue with the virtualbox.org domain. 
It should be solved by now.
