### ISSUE TITLE
ORACLE_BASE = /opt/oracle already exists

### ISSUE THREAD

**Issue by pewu78** [oracle/vagrant-boxes#47]
Just tried to spin up 12.2.0.1 DB, provisioning failed on this step:

```
# create directories
mkdir $ORACLE_BASE && \
chown oracle:oinstall -R $ORACLE_BASE && \
mkdir /u01/app && \
ln -s $ORACLE_BASE /u01/app/oracle
```
It seems the oracle dir already exists, which poses problem with above script (&&):

```
[root@oracle-12201-vagrant opt]# ll /opt
total 4
drwxr-xr-x. 2 root root    6 Jun 26 11:28 oracle
drwxr-xr-x. 9 root root 4096 Apr 24 08:06 VBoxGuestAdditions-5.1.24
```
>     oracle-12201-vagrant: INSTALLER: Oracle preinstall and openssl complete
>     oracle-12201-vagrant: mkdir:
>     oracle-12201-vagrant: cannot create directory ‘/opt/oracle’
>     oracle-12201-vagrant: : File exists
>     oracle-12201-vagrant: INSTALLER: Oracle directories created
>     ....
>     oracle-12201-vagrant: Preparing to launch Oracle Universal Installer from /tmp/OraInstall2018-06-26_11-49-22AM. Please wait ...
>     oracle-12201-vagrant: [FATAL] [INS-32012] Unable to create directory: /opt/oracle, on this server.
>     oracle-12201-vagrant:    CAUSE: Either proper permissions were not granted to create the directory or there was no space left in the volume.
>     oracle-12201-vagrant:    ACTION: Check your permission on the selected directory or choose another directory.
>     oracle-12201-vagrant: [FATAL] [INS-32012] Unable to create directory: /opt/oracle/product/12.2.0.1/dbhome_1, on this server.
>     oracle-12201-vagrant:    CAUSE: Either proper permissions were not granted to create the directory or there was no space left in the volume.
>     oracle-12201-vagrant:    ACTION: Check your permission on the selected directory or choose another directory.
> 

mkdir -p ?

**Comment by gvenzl** [comment]
Hm, I cannot reproduce that issue. Can you share what your `$ORACLE_BASE` is set in the Vagrantfile (if changed) and how you are provisioning the VM?

**Comment by gvenzl** [comment]
I think regardless we can just happily add the `-p` but just would like to understand why you are receiving this.

**Comment by pewu78** [comment]
I left the locations at defaults. That was second run of provisioning, initial attempt failed on yum upgrade - had to add proxy setting, so quite possibly it only created the dir before.

**Comment by gvenzl** [comment]
The directories are created after `yum upgrade` and co. Guess depending when you killed the provisioning and how you resumed it. Anyway, will add the`-p` in any case, won't do any harm.

**Comment by pewu78** [comment]
I let it run to completion ( fail fast :) ), so I guess mkdir succeded and chown failed (no oracle user).
It's not easy to make this process restartable - surely it's easier just to start from scratch, but in this case I had no choice. Thanks!

**Comment by pewu78** [comment]
Actually I've immediately added echo 'proxy=http://myhost:3128' >> /etc/yum.conf to install.sh script to avoid this in the future, but ran provisioning again on the existing box...
Should be easy to add proxy as an option.
