### ISSUE TITLE
Database 11.2.0.2 box installer directory (/vagrant/Disk1) not removed

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#50]
The `install.sh` script for the Oracle Database 11.2.0.2 box unzips the installer file (oracle-xe-11.2.0-1.0.x86_64.rpm.zip) to `/vagrant`. This creates a directory called `/vagrant/Disk1`. After Oracle XE is installed, `install.sh` tries to remove this directory. However, two of the files under `/vagrant/Disk1` are extracted without write permissions:

```
[vagrant@oracle11g-xe-vagrant ~]$ ls -l /vagrant/Disk1/response/xe.rsp /vagrant/Disk1/upgrade/gen_inst.sql
-r-xr-xr-x. 1 vagrant vagrant  2748 May 16  2011 /vagrant/Disk1/response/xe.rsp
-r-xr-xr-x. 1 vagrant vagrant 10285 Aug 29  2011 /vagrant/Disk1/upgrade/gen_inst.sql
```

As a result, the `rm -rf /vagrant/Disk1` command doesn't fully remove the directory. The following messages are shown during `vagrant up` when `install.sh` tries to remove the directory:

```
oracle11g-xe-vagrant: rm: cannot remove ‘/vagrant/Disk1/response/xe.rsp’: Operation not permitted
oracle11g-xe-vagrant: rm: cannot remove ‘/vagrant/Disk1/upgrade/gen_inst.sql’: Operation not permitted
```

This causes a couple of problems:
- After a `vagrant destroy`, the user must change permissions on the two files and remove `/vagrant/Disk1`. If this isn't done before a subsequent `vagrant up` operation, unzipping the installer will fail, and Oracle XE won't be installed.
- It's easy to accidentally commit the two files in git.

A simple solution is to change permissions on the directory `/vagrant/Disk1` before removing it. Adding the command `chmod -R o+w /vagrant/Disk1` in `install.sh` immediately before the `rm -rf /vagrant/Disk1` command fixes the issue.

Since this is a minor change, I'll go ahead and submit a pull request.

**Comment by gvenzl** [comment]
Merged!
