### ISSUE TITLE
node-work2 status is NotReady,why?

### ISSUE THREAD

**Issue by owen76512911** [oracle/vagrant-boxes#54]
vagrant up worker2 creating and starting both are normal, BUT, Kubectl get nodes shows Node-workd2 is NotReady! why? thanks in advance.

Best regards,
owen
----issue-info-
$ kubectl get nodes
NAME                 STATUS     ROLES     AGE       VERSION
master.vagrant.vm    Ready      master    40m       v1.9.1+2.1.5.el7
worker1.vagrant.vm   Ready      <none>    23m       v1.9.1+2.1.5.el7
worker2.vagrant.vm   NotReady   <none>    9m        v1.9.1+2.1.5.el7

----vagrant up work2----
vagrant up worker2
Bringing machine 'worker2' up with 'virtualbox' provider...
==> worker2: Importing base box 'ol7-latest'...
==> worker2: Matching MAC address for NAT networking...
==> worker2: Setting the name of the VM: Kubernetes_worker2_1530192939894_22077
==> worker2: Fixed port collision for 22 => 2222. Now on port 2201.
==> worker2: Clearing any previously set network interfaces...
==> worker2: Preparing network interfaces based on configuration...
    worker2: Adapter 1: nat
    worker2: Adapter 2: hostonly
==> worker2: Forwarding ports...
    worker2: 22 (guest) => 2201 (host) (adapter 1)
==> worker2: Running 'pre-boot' VM customizations...
==> worker2: Booting VM...
==> worker2: Waiting for machine to boot. This may take a few minutes...
    worker2: SSH address: 127.0.0.1:2201
    worker2: SSH username: vagrant
    worker2: SSH auth method: private key
    worker2: 
    worker2: Vagrant insecure key detected. Vagrant will automatically replace
    worker2: this with a newly generated keypair for better security.
    worker2: 
    worker2: Inserting generated public key within guest...
    worker2: Removing insecure key from the guest if it's present...
    worker2: Key inserted! Disconnecting and reconnecting using new SSH key...
==> worker2: Machine booted and ready!
==> worker2: Checking for guest additions in VM...
==> worker2: Setting hostname...
==> worker2: Configuring and enabling network interfaces...
    worker2: SSH address: 127.0.0.1:2201
    worker2: SSH username: vagrant
    worker2: SSH auth method: private key
==> worker2: Automatic installation for Landrush IP not enabled
==> worker2: Mounting shared folders...
    worker2: /vagrant => /Users/biyang/k8s/labs/vagrant-boxes/Kubernetes
==> worker2: Running provisioner: shell...
    worker2: Running: /var/folders/2m/bjrpx9zj1mn0q120w4cgg_b80000gn/T/vagrant-shell20180628-47236-qod999.sh
    worker2: Installing and configuring Docker Engine
    worker2: Package btrfs-progs-4.9.1-1.0.2.el7.x86_64 already installed and latest version
    worker2: Resolving Dependencies
    worker2: --> Running transaction check
    worker2: ---> Package docker-engine.x86_64 0:17.12.1.ol-1.0.3.el7 will be installed
    worker2: --> Processing Dependency: container-selinux >= 2.9 for package: docker-engine-17.12.1.ol-1.0.3.el7.x86_64
    worker2: --> Processing Dependency: libcgroup for package: docker-engine-17.12.1.ol-1.0.3.el7.x86_64
    worker2: --> Processing Dependency: libltdl.so.7()(64bit) for package: docker-engine-17.12.1.ol-1.0.3.el7.x86_64
    worker2: --> Running transaction check
    worker2: ---> Package container-selinux.noarch 2:2.21-1.el7 will be installed
    worker2: --> Processing Dependency: policycoreutils-python for package: 2:container-selinux-2.21-1.el7.noarch
    worker2: ---> Package libcgroup.x86_64 0:0.41-15.el7 will be installed
    worker2: ---> Package libtool-ltdl.x86_64 0:2.4.2-22.el7_3 will be installed
    worker2: --> Running transaction check
    worker2: ---> Package policycoreutils-python.x86_64 0:2.5-22.0.1.el7 will be installed
    worker2: --> Processing Dependency: audit-libs-python >= 2.1.3-4 for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Processing Dependency: setools-libs >= 3.3.8-2 for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Processing Dependency: libsemanage-python >= 2.5-9 for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Processing Dependency: python-IPy for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Processing Dependency: libqpol.so.1(VERS_1.2)(64bit) for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Processing Dependency: libqpol.so.1(VERS_1.4)(64bit) for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Processing Dependency: checkpolicy for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Processing Dependency: libapol.so.4(VERS_4.0)(64bit) for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Processing Dependency: libapol.so.4()(64bit) for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Processing Dependency: libqpol.so.1()(64bit) for package: policycoreutils-python-2.5-22.0.1.el7.x86_64
    worker2: --> Running transaction check
    worker2: ---> Package audit-libs-python.x86_64 0:2.8.1-3.el7 will be installed
    worker2: ---> Package checkpolicy.x86_64 0:2.5-6.el7 will be installed
    worker2: ---> Package libsemanage-python.x86_64 0:2.5-11.el7 will be installed
    worker2: ---> Package python-IPy.noarch 0:0.75-6.el7 will be installed
    worker2: ---> Package setools-libs.x86_64 0:3.3.8-2.el7 will be installed
    worker2: --> Finished Dependency Resolution
    worker2: 
    worker2: Dependencies Resolved
    worker2: 
    worker2: ================================================================================
    worker2:  Package                  Arch     Version                  Repository     Size
    worker2: ================================================================================
    worker2: Installing:
    worker2:  docker-engine            x86_64   17.12.1.ol-1.0.3.el7     ol7_preview    31 M
    worker2: Installing for dependencies:
    worker2:  audit-libs-python        x86_64   2.8.1-3.el7              ol7_latest     75 k
    worker2:  checkpolicy              x86_64   2.5-6.el7                ol7_latest    294 k
    worker2:  container-selinux        noarch   2:2.21-1.el7             ol7_addons     28 k
    worker2:  libcgroup                x86_64   0.41-15.el7              ol7_latest     65 k
    worker2:  libsemanage-python       x86_64   2.5-11.el7               ol7_latest    112 k
    worker2:  libtool-ltdl             x86_64   2.4.2-22.el7_3           ol7_latest     48 k
    worker2:  policycoreutils-python   x86_64   2.5-22.0.1.el7           ol7_latest    454 k
    worker2:  python-IPy               noarch   0.75-6.el7               ol7_latest     32 k
    worker2:  setools-libs             x86_64   3.3.8-2.el7              ol7_latest    619 k
    worker2: 
    worker2: Transaction Summary
    worker2: ================================================================================
    worker2: Install  1 Package (+9 Dependent packages)
    worker2: Total download size: 32 M
    worker2: Installed size: 128 M
    worker2: Downloading packages:
    worker2: --------------------------------------------------------------------------------
    worker2: Total                                              4.1 MB/s |  32 MB  00:07     
    worker2: Running transaction check
    worker2: Running transaction test
    worker2: Transaction test succeeded
    worker2: Running transaction
    worker2:   Installing : libcgroup-0.41-15.el7.x86_64                                1/10
    worker2:  
    worker2:   Installing : audit-libs-python-2.8.1-3.el7.x86_64                        2/10
    worker2:  
    worker2:   Installing : checkpolicy-2.5-6.el7.x86_64                                3/10
    worker2:  
    worker2:   Installing : libtool-ltdl-2.4.2-22.el7_3.x86_64                          4/10
    worker2:  
    worker2:   Installing : python-IPy-0.75-6.el7.noarch                                5/10
    worker2:  
    worker2:   Installing : libsemanage-python-2.5-11.el7.x86_64                        6/10
    worker2:  
    worker2:   Installing : setools-libs-3.3.8-2.el7.x86_64                             7/10
    worker2:  
    worker2:   Installing : policycoreutils-python-2.5-22.0.1.el7.x86_64                8/10
    worker2:  
    worker2:   Installing : 2:container-selinux-2.21-1.el7.noarch                       9/10
    worker2:  
    worker2:   Installing : docker-engine-17.12.1.ol-1.0.3.el7.x86_64                  10/10
    worker2:  
    worker2:   Verifying  : libcgroup-0.41-15.el7.x86_64                                1/10
    worker2:  
    worker2:   Verifying  : setools-libs-3.3.8-2.el7.x86_64                             2/10
    worker2:  
    worker2:   Verifying  : libsemanage-python-2.5-11.el7.x86_64                        3/10
    worker2:  
    worker2:   Verifying  : 2:container-selinux-2.21-1.el7.noarch                       4/10
    worker2:  
    worker2:   Verifying  : python-IPy-0.75-6.el7.noarch                                5/10
    worker2:  
    worker2:   Verifying  : libtool-ltdl-2.4.2-22.el7_3.x86_64                          6/10
    worker2:  
    worker2:   Verifying  : docker-engine-17.12.1.ol-1.0.3.el7.x86_64                   7/10
    worker2:  
    worker2:   Verifying  : policycoreutils-python-2.5-22.0.1.el7.x86_64                8/10
    worker2:  
    worker2:   Verifying  : checkpolicy-2.5-6.el7.x86_64                                9/10
    worker2:  
    worker2:   Verifying  : audit-libs-python-2.8.1-3.el7.x86_64                       10/10
    worker2:  
    worker2: 
    worker2: Installed:
    worker2:   docker-engine.x86_64 0:17.12.1.ol-1.0.3.el7                                   
    worker2: 
    worker2: Dependency Installed:
    worker2:   audit-libs-python.x86_64 0:2.8.1-3.el7                                        
    worker2:   checkpolicy.x86_64 0:2.5-6.el7                                                
    worker2:   container-selinux.noarch 2:2.21-1.el7                                         
    worker2:   libcgroup.x86_64 0:0.41-15.el7                                                
    worker2:   libsemanage-python.x86_64 0:2.5-11.el7                                        
    worker2:   libtool-ltdl.x86_64 0:2.4.2-22.el7_3                                          
    worker2:   policycoreutils-python.x86_64 0:2.5-22.0.1.el7                                
    worker2:   python-IPy.noarch 0:0.75-6.el7                                                
    worker2:   setools-libs.x86_64 0:3.3.8-2.el7                                             
    worker2: Complete!
    worker2: Creating 'btrfs' file system on: /dev/sdb
    worker2: Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.
    worker2: Installing and configuring Kubernetes packages
    worker2: Resolving Dependencies
    worker2: --> Running transaction check
    worker2: ---> Package kubeadm.x86_64 0:1.9.1-2.1.5.el7 will be installed
    worker2: --> Processing Dependency: kubectl >= 1.9.1-2.1.5.el7 for package: kubeadm-1.9.1-2.1.5.el7.x86_64
    worker2: --> Processing Dependency: kubernetes-cni >= 0.6.0 for package: kubeadm-1.9.1-2.1.5.el7.x86_64
    worker2: --> Processing Dependency: kubelet >= 1.9.1-2.1.5.el7 for package: kubeadm-1.9.1-2.1.5.el7.x86_64
    worker2: --> Running transaction check
    worker2: ---> Package kubectl.x86_64 0:1.9.1-2.1.5.el7 will be installed
    worker2: ---> Package kubelet.x86_64 0:1.9.1-2.1.5.el7 will be installed
    worker2: --> Processing Dependency: socat for package: kubelet-1.9.1-2.1.5.el7.x86_64
    worker2: ---> Package kubernetes-cni.x86_64 0:0.6.0-2.0.1.el7 will be installed
    worker2: --> Processing Dependency: kubernetes-cni-plugins = 0.6.0 for package: kubernetes-cni-0.6.0-2.0.1.el7.x86_64
    worker2: --> Running transaction check
    worker2: ---> Package kubernetes-cni-plugins.x86_64 0:0.6.0-2.0.1.el7 will be installed
    worker2: ---> Package socat.x86_64 0:1.7.3.2-2.el7 will be installed
    worker2: --> Finished Dependency Resolution
    worker2: 
    worker2: Dependencies Resolved
    worker2: 
    worker2: ================================================================================
    worker2:  Package                    Arch       Version             Repository      Size
    worker2: ================================================================================
    worker2: Installing:
    worker2:  kubeadm                    x86_64     1.9.1-2.1.5.el7     ol7_addons      17 M
    worker2: Installing for dependencies:
    worker2:  kubectl                    x86_64     1.9.1-2.1.5.el7     ol7_addons     8.9 M
    worker2:  kubelet                    x86_64     1.9.1-2.1.5.el7     ol7_addons      17 M
    worker2:  kubernetes-cni             x86_64     0.6.0-2.0.1.el7     ol7_addons     797 k
    worker2:  kubernetes-cni-plugins     x86_64     0.6.0-2.0.1.el7     ol7_addons     8.5 M
    worker2:  socat                      x86_64     1.7.3.2-2.el7       ol7_latest     289 k
    worker2: 
    worker2: Transaction Summary
    worker2: ================================================================================
    worker2: Install  1 Package (+5 Dependent packages)
    worker2: Total download size: 52 M
    worker2: Installed size: 279 M
    worker2: Downloading packages:
    worker2: --------------------------------------------------------------------------------
    worker2: Total                                              5.8 MB/s |  52 MB  00:08     
    worker2: Running transaction check
    worker2: Running transaction test
    worker2: Transaction test succeeded
    worker2: Running transaction
    worker2:   Installing : socat-1.7.3.2-2.el7.x86_64                                   1/6
    worker2:  
    worker2:   Installing : kubelet-1.9.1-2.1.5.el7.x86_64                               2/6
    worker2:  
    worker2:   Installing : kubectl-1.9.1-2.1.5.el7.x86_64                               3/6
    worker2:  
    worker2:   Installing : kubernetes-cni-plugins-0.6.0-2.0.1.el7.x86_64                4/6
    worker2:  
    worker2:   Installing : kubernetes-cni-0.6.0-2.0.1.el7.x86_64                        5/6
    worker2:  
    worker2:   Installing : kubeadm-1.9.1-2.1.5.el7.x86_64                               6/6
    worker2:  
    worker2:   Verifying  : kubernetes-cni-plugins-0.6.0-2.0.1.el7.x86_64                1/6
    worker2:  
    worker2:   Verifying  : kubeadm-1.9.1-2.1.5.el7.x86_64                               2/6
    worker2:  
    worker2:   Verifying  : kubernetes-cni-0.6.0-2.0.1.el7.x86_64                        3/6
    worker2:  
    worker2:   Verifying  : kubectl-1.9.1-2.1.5.el7.x86_64                               4/6
    worker2:  
    worker2:   Verifying  : socat-1.7.3.2-2.el7.x86_64                                   5/6
    worker2:  
    worker2:   Verifying  : kubelet-1.9.1-2.1.5.el7.x86_64                               6/6
    worker2:  
    worker2: 
    worker2: Installed:
    worker2:   kubeadm.x86_64 0:1.9.1-2.1.5.el7                                              
    worker2: 
    worker2: Dependency Installed:
    worker2:   kubectl.x86_64 0:1.9.1-2.1.5.el7                                              
    worker2:   kubelet.x86_64 0:1.9.1-2.1.5.el7                                              
    worker2:   kubernetes-cni.x86_64 0:0.6.0-2.0.1.el7                                       
    worker2:   kubernetes-cni-plugins.x86_64 0:0.6.0-2.0.1.el7                               
    worker2:   socat.x86_64 0:1.7.3.2-2.el7                                                  
    worker2: Complete!
    worker2: net.bridge.bridge-nf-call-ip6tables = 1
    worker2: net.bridge.bridge-nf-call-iptables = 1
    worker2: Your Kubernetes VM is ready to use!

--------
$ vagrant status
Current machine states:

master                    running (virtualbox)
worker1                   running (virtualbox)
worker2                   running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
Yangs-MacBook-Pro:Kubernetes biyang$ vagrant ssh master
Last login: Thu Jun 28 13:02:06 2018 from 10.0.2.2
  
Welcome to Oracle Linux Server release 7.5 (GNU/Linux 4.1.12-124.14.1.el7uek.x86_64)
  
The Oracle Linux End-User License Agreement can be viewed here:
  
    * /usr/share/eula/eula.en_US

For additional packages, updates, documentation and community help, see: 
  
    * http://yum.oracle.com/
  
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
---------
get nodes
NAME                 STATUS     ROLES     AGE       VERSION
master.vagrant.vm    Ready      master    40m       v1.9.1+2.1.5.el7
worker1.vagrant.vm   Ready      <none>    23m       v1.9.1+2.1.5.el7
worker2.vagrant.vm   NotReady   <none>    9m        v1.9.1+2.1.5.el7
------
get pods --namespace=kube-system
NAME                                        READY     STATUS     RESTARTS   AGE
etcd-master.vagrant.vm                      1/1       Running    0          42m
kube-apiserver-master.vagrant.vm            1/1       Running    0          41m
kube-controller-manager-master.vagrant.vm   1/1       Running    0          41m
kube-dns-855949bbf-b2ldn                    3/3       Running    0          42m
kube-flannel-ds-hvl54                       0/1       Init:0/1   0          12m
kube-flannel-ds-j9bq2                       1/1       Running    0          26m
kube-flannel-ds-thpr7                       1/1       Running    0          42m
kube-proxy-4hmmw                            1/1       Running    0          26m
kube-proxy-q2vmp                            1/1       Running    0          12m
kube-proxy-sj6lj                            1/1       Running    0          42m
kube-scheduler-master.vagrant.vm            1/1       Running    0          42m
kubernetes-dashboard-7c966ddf6d-l2r7n       1/1       Running    0          42m
------

**Comment by owen76512911** [comment]
That's funny. The problem's gone! The root cause: I'm sure, is that the initialization of worker2 is not over.
Anyway, the problem is solved.
---
`kubectl get nodes`
NAME                 STATUS    ROLES     AGE       VERSION
master.vagrant.vm    Ready     master    52m       v1.9.1+2.1.5.el7
worker1.vagrant.vm   Ready     <none>    35m       v1.9.1+2.1.5.el7
worker2.vagrant.vm   Ready     <none>    21m       v1.9.1+2.1.5.el7

**Comment by AmedeeBulle** [comment]
Yes, this is _normal_, it takes a couple of minutes between the end of the install script and the node to be fully ready.
