### ISSUE TITLE
Is there a Vagrant box available for Oracle BCC ?

### ISSUE THREAD

**Issue by sachinlala** [oracle/vagrant-boxes#57]
Hi Team:

Is there a Vagrant box available for Oracle BCC (Business Control Center) ? I could not find it in this repository. Will be very helpful if it can be added.

Thanks.
Sachin

**Comment by sachinlala** [comment]
Hi @gvenzl, team - please can you check this ?

**Comment by totalamateurhour** [comment]
We will check with the product team responsible for BCC.

**Comment by gvenzl** [comment]
We checked with the BCC development group and currently they have no plans on supporting BCC in such an environment.
