### ISSUE TITLE
kubernetes cluster: "Waiting for kubeadm to setup master cluster" for a long time

### ISSUE THREAD

**Issue by v-dev** [oracle/vagrant-boxes#58]
Hello. I followed instructions here:
https://geraldonit.com/2018/03/26/deploying-a-kubernetes-cluster-with-vagrant-on-virtual-box/

On my master vagrant vm, as root, I ran:

    [root@master bin]# /vagrant/scripts/kubeadm-setup-master.sh

After more than 10 minutes, I still see "... Setup Master node -- be patient!"  Tailing the log shows 0% complete:

    [root@master bin]# tail -f kubeadm-setup.log 
    Starting to initialize master node ...
    Checking if env is ready ...
    Checking whether docker can pull busybox image ...
    Checking access to container-registry.oracle.com/kubernetes ...
    v1.9.1-1: Pulling from kubernetes/kube-proxy-amd64
    Digest: sha256:f525d06eebf7f21c55550b1da8cee4720e36b9ffee8976db357f49eddd04c6d0
    Status: Image is up to date for container-registry.oracle.com/kubernetes/kube-proxy-amd64:v1.9.1-1
    Checking whether docker can run container ...
    Checking iptables default rule ...
    Checking br_netfilter module ...
    Checking sysctl variables ...
    Check successful, ready to run 'up' command ...
    Waiting for kubeadm to setup master cluster...
    Please wait ...
    | - 0% completed

Running on macOS 10.12.6:
<img width="259" alt="screen shot 2018-07-19 at 11 09 16 pm" src="https://user-images.githubusercontent.com/1215209/42984281-0c073d68-8ba9-11e8-925d-6ae2f9cab1d9.png">

VirtualBox 5.2.12 r122591 (Qt5.6.3)
Vagrant 2.1.1

How "patient" should I be?  And/or what am I doing wrong?

**Comment by AmedeeBulle** [comment]
`container-registry.oracle.com` is sometimes overloaded and can be very slow.

I strongly recommend using one of the registry mirrors in your area for better performance -- See [Registry Mirror](/oracle/vagrant-boxes/tree/master/Kubernetes#registry-mirror) in the README.

With a registry mirror configured it should not take more than 5 to 10 minutes to download the images and provision the master.

In case it doesn't work with a registry mirror, then wen need to look at you network configuration, but I believe it should be good as it can successfully download `kube-proxy-amd64`.

**Comment by v-dev** [comment]
I didn't realize it was trying to download more images. It just seemed "hung." It would be nice if there was some indication of what it was trying to do so I know to wait longer instead of thinking something was wrong.

I will try a closer (and/or local) registry. Is there a way for me to find a list of the images it's trying to download so I can pre `docker pull` them?

**Comment by v-dev** [comment]
I apologize - I was tl;dr'ing and didn't RTM. I missed the part about accepting the license terms for the _entire_ "Container Services" business area. I only accepted the terms for the first image I ran into: `kube-proxy-amd64`.  After this, I was able to run `/vagrant/scripts/kubeadm-setup-registry.sh` successfully. I'll now see about using this for my Kubernetes setup.

That also answers my question as to the list of images it needs.

**Comment by v-dev** [comment]
Thanks! Yes - not accepting terms for the _entire_ "Container Services" business area was my problem. And great tip on using ContainerRegistry - very helpful.

My only request would be to make it more clear somewhere (in the logs/output?) during provisioning if there are image download problems so people know where to start investigating.

I'll close out this issue now.
