### ISSUE TITLE
How Can I configure external kubectl to control the vagrant kubernetes cluster?

### ISSUE THREAD

**Issue by stevanikof** [oracle/vagrant-boxes#62]
I deployed a master + 3 node k8s cluster (on OSX)
From the master node I borrowed the ~/.kube/config file and placed in my ~/.kube/config on my Mac
Using HomeBrew, installed the kubectl package. This has worked before against minikube

Not able to communicate with the cluster

The master appears to have port 6443 mapped out on the host only adapter but I can't seem to connect/netcat to it

**Comment by gvenzl** [comment]
Hey @AmedeeBulle, do you thin we can close this as "assumed answered"?
