### ISSUE TITLE
Database box setPassword.sh script problem on Windows (Git EOL)

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#71]
On Windows hosts, the `setPassword.sh` scripts for the Oracle Database boxes fail. This seems to be the same Git for Windows end-of-line conversion issue that was reported recently for the Kubernetes box (#68).

Environment: Windows 10 Professional x64 Version 1803, VirtualBox 5.2.18, Vagrant 2.1.5, Git for Windows 2.19.0.

The following from the Oracle Database 12.2.0.1 box shows the issue. The 11g XE and 18c `setPassword.sh` scripts generate the same error.
```
[vagrant@oracle-12201-vagrant ~]$ sudo su - oracle
Last login: Sun Sep 16 16:54:02 -06 2018
[oracle@oracle-12201-vagrant ~]$ ./setPassword.sh TopSecret
-bash: ./setPassword.sh: /bin/bash^M: bad interpreter: No such file or directory
```
To confirm that end-of-line conversion is the problem, I made a copy of the `setPassword.sh` script with the CR characters removed. The copy worked correctly.
```
[oracle@oracle-12201-vagrant ~]$ tr -d '\r' < setPassword.sh > setPassword2.sh
[oracle@oracle-12201-vagrant ~]$ chmod a+rx setPassword2.sh
[oracle@oracle-12201-vagrant ~]$ ./setPassword2.sh TopSecret
The Oracle base remains unchanged with value /opt/oracle
...
<script runs normally>
...
SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
```
I've verified that the same `.gitattributes` file that @AmedeeBulle created to fix this issue for the ContainerRegistry and Kubernetes boxes also fixes it for the database boxes.

If you agree that this is a legitimate issue, and that adding `.gitattributes` files is the right solution, I'd be happy to submit a PR.

**Comment by AmedeeBulle** [comment]
My bad -- I though I was the only one running shell scripts from the guests, so I didn't looked at other boxes.

PR is welcome, thanks for spotting this.

**Comment by PaulNeumann** [comment]
Thank you, sir.  PR submitted.

**Comment by gvenzl** [comment]
Merged! Thanks for the contribution, @PaulNeumann
