### ISSUE TITLE
Database 18c XE box

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#75]
Congratulations on the release of Oracle Database 18c XE! Very nice!

As a learning exercise, I built a Vagrant box for 18c XE, based on the other database boxes in this repository. (You can see it in my fork [here](https://github.com/PaulNeumann/vagrant-boxes/tree/oracle_db_18c_XE_box/OracleDatabase/18.4.0-XE).)

I wanted to share a couple of things I found, in case they help someone else (and in case someone has better solutions!). Some of this might be environment-specific. I used VirtualBox 5.2.20 and Vagrant 2.2.0 on Windows 10 Professional x64 Version 1803.

* If the VM hostname is set in the `Vagrantfile` (`config.vm.hostname = NAME`), listener configuration fails. `oracle-xe-18c configure` errors out with the message `Listener configuration failed. Check log '/opt/oracle/cfgtoollogs/netca/netca_configure_out.log' for more details.`

   `/opt/oracle/cfgtoollogs/netca/netca_configure_out.log` includes the following:
   ```
   Oracle Net Listener Startup:
   No valid IP Address returned for the host oracle18c-xe-vagrant.
   Check the trace file for details: /opt/oracle/cfgtoollogs/netca/trace_OraHomeXE-1810226PM1428.log
   Oracle Net Services configuration failed.  The exit code is 1
   ```
   Since listener configuration fails, the rest of the configuration is skipped, and the database isn't created. To avoid this problem, don't specify a VM hostname in the `Vagrantfile`. The hostname then defaults to localhost, which seems OK in this case.

   (Interestingly, if you `ssh` to the box after the configuration fails and run `oracle-xe-18c configure` again, it works. But that doesn't help with a non-interactive installation.)

* The preinstall rpm is automatically pulled when the database rpm is installed, but it doesn't create the oracle user's home directory (`/home/oracle`), which means that oracle's database-related environment variables can't easily be set in `.bashrc`, and `sudo su - oracle` doesn't work quite as expected.

   However, if you install the preinstall rpm separately before installing the database rpm, `/home/oracle` is created normally. This doesn't seem to be a Vagrant issue--the same behavior occurs using a clean VM installed from the OL7.5 iso.

* If you edit the `oracle-xe-18c.conf` file on a Windows host, be sure to preserve the Unix (LF) line endings. `oracle-xe-18c configure` won't work if the configuration file uses DOS (CR/LF) line endings.

I hope this helps. Again, congratulations on the release.

**Comment by gvenzl** [comment]
Thank you very much for the heads-up and the congratulations, @PaulNeumann!
We will have a look at all of them.

**Comment by gvenzl** [comment]
@PaulNeumann, do you want to PR this back into main? Otherwise I'm happy to provide an XE Vagrant box myself.

**Comment by PaulNeumann** [comment]
@gvenzl, I'm happy to submit a PR for this. Thanks!

**Comment by maslovd1978** [comment]
Hi.
I've found your post looking for the solution of this problem: "LISTENER:No valid IP Address returned for the host ......"

In my case I had to change /etc/hosts from 

------------------------------------
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 myhost myhost.localdomain
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 myhost myhost.localdomain
------------------------------------

to
-----------------------------------
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.0.222 myhost
-----------------------------------
then Oracle 18 for Linux started listener and proceeded to DB creation.

**Comment by scoter-oracle** [comment]
An option to force the usage of "localhost" could be to add following command:

sed -i 's/HOSTNAME_CMD="\/bin\/hostname"/HOSTNAME_CMD="echo localhost"/' /etc/init.d/oracle-xe-18c

before executing the Database/Listener setup with "/etc/init.d/oracle-xe-18c configure"

Once the configuration has finished we can add back the original command, with:

sed -i 's/HOSTNAME_CMD="echo localhost"/HOSTNAME_CMD="\/bin\/hostname"/' /etc/init.d/oracle-xe-18c
