### ISSUE TITLE
question about 12.2.0.1

### ISSUE THREAD

**Issue by minoseah629** [oracle/vagrant-boxes#77]

**Comment by minoseah629** [comment]
I had an issue with starting up the vagrant environment.

I followed these instructions: 
https://github.com/oracle/vagrant-boxes/tree/master/OracleDatabase/12.2.0.1

```
C:\Repos\vagrant-boxes\OracleDatabase\12.2.0.1 [master ≡]> vagrant up
Bringing machine 'oracle-12201-vagrant' up with 'virtualbox' provider...
==> oracle-12201-vagrant: Clearing any previously set forwarded ports...
==> oracle-12201-vagrant: Clearing any previously set network interfaces...
==> oracle-12201-vagrant: Preparing network interfaces based on configuration...
    oracle-12201-vagrant: Adapter 1: nat
==> oracle-12201-vagrant: Forwarding ports...
    oracle-12201-vagrant: 1521 (guest) => 1521 (host) (adapter 1)
    oracle-12201-vagrant: 5500 (guest) => 5500 (host) (adapter 1)
    oracle-12201-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> oracle-12201-vagrant: Running 'pre-boot' VM customizations...
==> oracle-12201-vagrant: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "f6b29f02-df8f-428e-9ba6-f7ce1eecd8bd", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```

**Comment by gvenzl** [comment]
Looks like this is an issue between VirtualBox and Vagrant:

```
Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```

**Comment by minoseah629** [comment]
I looked around virtualbox and I did not see the vboxmanage.exe file.

I did see vboxheadless.

Version 5.2.20 r125813 (Qt5.6.2)

**Comment by minoseah629** [comment]
It was there, just missed it 
![image](https://user-images.githubusercontent.com/1980068/48152603-51c88b00-e292-11e8-9e91-be8a4c281c2e.png)

**Comment by PaulNeumann** [comment]
@minoseah629, this error means that VirtualBox isn't able to use VT-x, which is a set of hardware extensions for CPUs running virtual machines. An online search for "VirtualBox VT-x is not available" gives a **lot** of results. (The one [here](https://superuser.com/questions/1153470/vt-x-is-not-available-but-is-enabled-in-bios) is pretty helpful, in my opinion.)

Assuming that your CPU supports VT-x, which it probably does if it's fairly recent, the first thing to check is whether VT-x is enabled in your computer's BIOS. If it isn't, enable it. If that doesn't help, ensure that Hyper-V virtualization is disabled in Windows. The page I linked to above has instructions for that.

I hope this helps!

**Comment by minoseah629** [comment]
I think i forgot hyper v is on. ill let you know.

**Comment by minoseah629** [comment]
that was the problem. screenshot shows that i got passed boot vm in log. thanks @PaulNeumann.

![image](https://user-images.githubusercontent.com/1980068/48156954-7164b100-e29c-11e8-8fca-ebce5c894d9f.png)

**Comment by PaulNeumann** [comment]
Excellent! I'm glad it's working for you.
