### ISSUE TITLE
Database 12c R1 (12.1.0.2) box - Enhancement

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#81]
Would you consider an enhancement to add an Oracle Database 12c Release 1 (12.1.0.2) box? There are 12c R1 builds for EE and SE2 in the [docker-images repository](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles/12.1.0.2), and I think it'd be helpful to have it available as a Vagrant box, too--a lot of organizations still use 12c R1.

If you think this is a good idea, I have a 12c R1 box ready that supports both EE and SE2. It follows the same conventions as the other database boxes in this repository.

**Comment by gvenzl** [comment]
Hi @PaulNeumann,

12.1.0.2 is in waived extended support until July this year. Do you think it still makes sense providing such a box if it soon will run out of support?

**Comment by PaulNeumann** [comment]
Hi @gvenzl,

I think there would be some value in having a 12.1.0.2 box available. Although it's nearing end of support, there are still a lot of organizations using it. If nothing else, being able to easily spin up a 12.1.0.2 box could make migration planning and testing easier. That said, it's 100% up to you, and I'm OK with whatever you decide.

Thanks,
Paul

**Comment by PaulNeumann** [comment]
Hi @gvenzl,

Done.  I've submitted a PR for this.  I'm happy to make any changes that you'd like.

Thanks,
Paul

**Comment by gvenzl** [comment]
Looked good, thanks once again, @PaulNeumann! Merged!
