### ISSUE TITLE
Apex Port

### ISSUE THREAD

**Issue by attewell** [oracle/vagrant-boxes#82]
Can you add a port for Apex port

**Comment by scoter-oracle** [comment]
We're working on this. We hope to get it available soon.

**Comment by gvenzl** [comment]
You mean have port forwarding there for APEX on 8080?

**Comment by attewell** [comment]
For apex

**Comment by attewell** [comment]
Yes correct

**Comment by scoter-oracle** [comment]
The intention is to introduce an Vagrant Box dedicated to APEX so I do not see the value to add the port-forwarding here. Soon we should have news about the new box.

**Comment by AmedeeBulle** [comment]
Right...
Although there is nothing wrong with binding ports, they must be available on the host, so if we start binding the same port on all our boxes we will eventually get conflicts, not speaking about other services which might use the same port as well.
If we eventually decide to make it generic, it might be preferable to make it optional...

**Comment by gvenzl** [comment]
Closing in favor of the APEX Box
