### ISSUE TITLE
kubeadm-setup-master.sh seem to fail despite providing right credentials

### ISSUE THREAD

**Issue by kumarsb** [oracle/vagrant-boxes#83]
I am seeing https://github.com/oracle/vagrant-boxes/issues/25. Workaround mentioned does not solve the problem.

1. Attempting to setup maser

[root@master scripts]# ./kubeadm-setup-master.sh 
./kubeadm-setup-master.sh: Login to container-registry.oracle.com
Username: sathish......@oracle.com
Password: 
Login Succeeded
./kubeadm-setup-master.sh: Setup Master node -- be patient!
./kubeadm-setup-master.sh: kubeadm-setup.sh did not complete successfully
Last lines of kubeadm-setup.log:
Starting to initialize master node ...
Checking if env is ready ...
Checking whether docker can pull busybox image ...
Checking access to container-registry.oracle.com/kubernetes ...
[ERROR] Please login with valid credential to the container-registry.oracle.com/kubernetes
        # docker login container-registry.oracle.com/kubernetes

2. Try to do docker login. This is successful

[root@master scripts]# docker login container-registry.oracle.com/kubernetes
Username (sathish......@oracle.com): 
Password: 
Login Succeeded

3. Again try master setup. Failure again 

[root@master scripts]# ./kubeadm-setup-master.sh 
./kubeadm-setup-master.sh: Login to container-registry.oracle.com
Username (sathish......@oracle.com): 
Password: 
Login Succeeded
./kubeadm-setup-master.sh: Setup Master node -- be patient!
./kubeadm-setup-master.sh: kubeadm-setup.sh did not complete successfully
Last lines of kubeadm-setup.log:
Starting to initialize master node ...
Checking if env is ready ...
Checking whether docker can pull busybox image ...
Checking access to container-registry.oracle.com/kubernetes ...
[ERROR] Please login with valid credential to the container-registry.oracle.com/kubernetes
        # docker login container-registry.oracle.com/kubernetes
[root@master scripts]# 

Any help appreciated. Thanks Sathish

**Comment by AmedeeBulle** [comment]
A couple of questions:
- Are you installing the latest production or development release (`USE_DEV` parameter)
- Are you behind a firewall (Oracle intranet)? If yes, did you install vagrant-proxyconf plugin?

Thank you

**Comment by kumarsb** [comment]
I tried running kubeadm-setup.sh directly to see what is going on. 

**1. I made one small change to include docker login to that script.**

`
[root@master bin]# diff kubeadm-setup.sh kubeadm-setup.sh.old 
89,92d88

 #additions start
 docker login container-registry.oracle.com/kubernetes 
 #additions end
[root@master bin]# 
`

**2. I than invoke bash. See the log :** 

`
[root@master bin]# bash -x ./kubeadm-setup.sh up
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ set -o errtrace
+ REGISTRY=container-registry.oracle.com/kubernetes
+ KUBECONFIG=/etc/kubernetes/admin.conf
+ KUBELET_EXTRA=/etc/systemd/system/kubelet.service.d/20-pod-infra-image.conf
+ TAINT_CHECK=/var/run/kubeadm/.taint
+ TIMEOUT=500
+ K8S_VERSION=v1.9.1-1
+ KUBECTL='kubectl --kubeconfig=/etc/kubernetes/admin.conf -n kube-system'
+ trap cleanup 2
+ '[' 1 -lt 1 ']'
+ '[' up '!=' upgrade ']'
+ unsetproxy
+ unset http_proxy https_proxy
+ unset HTTP_PROXY HTTPS_PROXY
+ '[' 0 -ne 0 ']'
+ '[' -z '' ']'
+ ping -c1 -W1 169.254.169.254
+ OCI_CHECK=0
+ '[' 0 = 1 ']'
+ '[' '!' -d /var/run/kubeadm/ ']'
+ case "${1:-}" in
+ shift
+ kubeadm::up
+ local registry=
+ local podcidr=10.244.0.0/16
+ local netmask=
+ local skip=
+ local network=flannel
+ local api_port=6443
+ local certs_sans=0
+ arg=($@)
+ local arg
+ (( i=0 ))
+ (( i<0 ))
+ echo 'Starting to initialize master node ...'
Starting to initialize master node ...
+ kubeadm::down --skip
+ kubeadm::check master '' '' 6443 kube-proxy-amd64:v1.9.1-1
+ local vals=master
+ local repo=container-registry.oracle.com/kubernetes
+ local skip=
+ local extra=6443
+ local image=kube-proxy-amd64:v1.9.1-1
+ echo 'Checking if env is ready ...'
Checking if env is ready ...
++ kubeadm version -o short
++ awk -F. '{print $2}'
+ local version=9
+ '[' 9 -lt 6 ']'
+ grep -q /sbin
+ echo /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin
+ systemctl -q is-active docker
+ echo 'Checking whether docker can pull busybox image ...'
Checking whether docker can pull busybox image ...
+ docker login container-registry.oracle.com/kubernetes
Username (sathish......@oracle.com): 
Password: 
Login Succeeded
+ docker pull busybox
+ echo 'Checking access to container-registry.oracle.com/kubernetes ...'
Checking access to container-registry.oracle.com/kubernetes ...
+ check_repo container-registry.oracle.com/kubernetes kube-proxy-amd64:v1.9.1-1
+ local repo=container-registry.oracle.com/kubernetes
+ local image=kube-proxy-amd64:v1.9.1-1
++ echo ''
++ docker pull container-registry.oracle.com/kubernetes/kube-proxy-amd64:v1.9.1-1
++ grep 'login\|unauthorized: authentication required'
+ local 'result=pull access denied for container-registry.oracle.com/kubernetes/kube-proxy-amd64, repository does not exist or may require '\''docker login'\'''
+ '[' -n 'pull access denied for container-registry.oracle.com/kubernetes/kube-proxy-amd64, repository does not exist or may require '\''docker login'\''' ']'
+ echo '[ERROR] Please login with valid credential to the container-registry.oracle.com/kubernetes'
[ERROR] Please login with valid credential to the container-registry.oracle.com/kubernetes
+ echo '        # docker login container-registry.oracle.com/kubernetes'
        # docker login container-registry.oracle.com/kubernetes
+ exit 1
[root@master bin]# 
`

**Comment by AmedeeBulle** [comment]
Can you please double check you have accepted the license agreement on the [container registry](https://container-registry.oracle.com/pls/apex/f?p=113:1:::NO:1:P1_BUSINESS_AREA:27) for __all__ containers -- even if you accepted in the past, new release might ask you to re-confirm.

Ultimately you should be able to do on the command line:
```
docker login container-registry.oracle.com/kubernetes
docker pull container-registry.oracle.com/kubernetes/kube-proxy-amd64:v1.9.1-1
```

**Comment by kumarsb** [comment]
Thanks. Accepting the license agreement, kept me going.
.
If somehow the tool can either fail the authentication (docker login) or the docker pull based on license agreement, it would save time. If that it is not possible, the tool should output this message (please accept the license agreement.

Thanks. Sathush

**Comment by peeyushgoela** [comment]
For people who are still facing this issue, please make sure that you have the license agreement in "Container Services" tab of the "Oracle Container Registry"
