### ISSUE TITLE
Database boxes - run user-defined post-setup scripts

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#85]
Would you consider an enhancement to the Oracle Database boxes to allow running user-defined scripts after the database is set up?  Users often need to run shell and/or SQL scripts to finish setting up the environment after database installation, and this would automate the process.  The Oracle Database builds in the [docker-images](https://github.com/oracle/docker-images) repository have this feature, and it might be useful for the Vagrant database boxes, too.

In the docker-images repository, there's a script called [runUserScripts.sh](https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/dockerfiles/18.3.0/runUserScripts.sh) that runs user-defined scripts.  It's straightforward to add the same logic to the `install.sh` scripts for the database boxes:

```bash
# run user-defined post-setup scripts
echo 'INSTALLER: Running user-defined post-setup scripts'

for f in /vagrant/userscripts/*
  do
    case "${f,,}" in
      *.sh)
        echo "INSTALLER: Running $f"
        . "$f"
        echo "INSTALLER: Done running $f"
        ;;
      *.sql)
        echo "INSTALLER: Running $f"
        su -l oracle -c "echo 'exit' | sqlplus -s / as sysdba @\"$f\""
        echo "INSTALLER: Done running $f"
        ;;
      *)
        echo "INSTALLER: Ignoring $f"
        ;;
    esac
  done

echo 'INSTALLER: Done running user-defined post-setup scripts'
```

I've been using this for a while, and it seems to work well.  It runs any `.sh` and `.sql` scripts in the `/vagrant/userscripts` directory, and ignores other file extensions.  It handles both lower- and upper-case file extensions, and works for filenames with spaces in them.  The functionality is completely optional; if there aren't any script files in the directory, nothing is run.  I put this block right after `setPassword.sh` is set up.

To make this as easy to use as possible, it might make sense to add the `/vagrant/userscripts` directory, perhaps including a file called `put_custom_scripts_here.txt`.  Usage instructions could be placed in this file, as well as in `README.md`.

Do you think this would be worthwhile?  If so, I'd be happy to work on it.  I'd also be grateful for any suggested improvements.

**Comment by gvenzl** [comment]
Hey @PaulNeumann,

Yeah, I think that would make a lot of sense, also to keep symmetry with the Docker build files as well. I like your idea of putting also a text file in the folder with instructions (as well as adding them to the README.md).
The only thing I would add then is to ignore that file, so that it doesn't always produce a "INSTALLER: Ignoring put_custom_scripts_here.txt".

**Comment by PaulNeumann** [comment]
Thanks! Ignoring `put_custom_scripts_here.txt` is a great idea--I appreciate it.

I've submitted a PR for this. I'm happy to make any changes that you'd like.

**Comment by gvenzl** [comment]
Thanks a lot, @PaulNeumann!

Your PR is now merged!
