### ISSUE TITLE
Workaround for shared folders not working after reboot

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#87]
**This isn't a requested change, it's just a workaround for a temporary shared folder issue.**

The latest UEK Release 5 kernel releases for Oracle Linux 7 and the latest version of the VirtualBox Guest Additions kernel module apparently aren't totally compatible. As a result, VirtualBox shared folders don't work. This isn't related to the boxes in this repository, but it affects new boxes built using the latest version of the OL7 base box.

If you're affected by this problem, the box will build fine, but after a reboot, shared folders (including `/vagrant`) won't work. Here's what seems to be happening:
* All of the OL7-based boxes are built on top of the base box called `ol7-latest.box`. The current version of the base box includes the UEK Release 5 kernel and the VirtualBox Guest Additions kernel module. This kernel module provides the shared folder functionality.

* When starting a box for the first time, installed packages are updated to the latest versions by the command `yum upgrade -y` in the install script. During the update, the kernel is upgraded to version 4.14.35-1818.4.7.el7uek.x86_64, and the VirtualBox Guest Additions kernel module is upgraded to version 5.2.20	(kmod-vboxguest-uek5-5.2.20-1.el7.x86_64).

* When the guest is rebooted (`vagrant halt` / `vagrant up`), the new kernel version is loaded. With this new kernel version, the updated Guest Additions kernel module no longer provides shared folder functionality. You'll see something like the following when you run `vagrant up`. The exact text may vary depending on host OS:
```
      ==> ol7-vagrant: Mounting shared folders...
      ol7-vagrant: /vagrant => C:/vagrant-boxes/OracleLinux/7
      Vagrant was unable to mount VirtualBox shared folders. This is usually
      because the filesystem "vboxsf" is not available. This filesystem is
      made available via the VirtualBox Guest Additions and kernel module.
      Please verify that these guest additions are properly installed in the
      guest. This is not a bug in Vagrant and is usually caused by a faulty
      Vagrant box. For context, the command attempted was:

      mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

      The error output from the command was:

      /sbin/mount.vboxsf: mounting failed with the error: No such device
```

If you're seeing this, you can work around it by downgrading the kernel:
* Run `vagrant ssh`.

* In the SSH session, run `sudo yum -y install kernel-uek-4.14.35-1818.3.3.el7uek.x86_64`, then reboot the VM. (Version 4.14.35-1818.3.3.el7uek.x86_64 of the UEK Release 5 kernel seems to be the latest version that works properly with version 5.2.20 of the VirtualBox Guest Additions kernel module.)

I'm sure this will be fixed soon with a new release of the Guest Additions kernel module and/or the kernel. In the meantime, I hope this helps.

**Comment by PaulNeumann** [comment]
**Update**:  A new version of the UEK Release 5 kernel has been released, version 4.14.35-1818.**5.4**.el7uek.x86_64.  Unfortunately, it doesn't seem to resolve the problem.  The workaround described above is still valid.

**Comment by scoter-oracle** [comment]
Paul,

the easiest work-around with latest OL7.6 image is to just reload the vagrant box (#vagrant reload) or to connect to the same (#vagrant ssh) and then mount the shared-folders with:

# mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

Actually the VM is autonomous to get VBox modules recompiled while the kernel change, the issue is related to the time required to get VBox modules available for the updated kernel.

**Comment by PaulNeumann** [comment]
@scoter-oracle,

Thanks! Yes, the OL 7.6 base box that was released a couple of days ago fixes the problem.

The new base box doesn't use the VirtualBox Guest Additions kernel module (kmod-vboxguest-uek5). Instead, it has version 5.2.22 of the Guest Additions pre-installed under `/opt`. When starting a Vagrant box that uses this new base box for the first time, the kernel is still upgraded, and shared folders continue to work after a reboot.

For those who might still be using the previous version of the base box, the workaround described above is still valid, but upgrading the base box is a better solution.

I appreciate your help. I'll go ahead and close this issue.
