### ISSUE TITLE
bug? hangs at "vagrant up master" for vagrant-boxes/Kubernetes

### ISSUE THREAD

**Issue by erikhSSI** [oracle/vagrant-boxes#88]
(Note: similar symptoms to issue #24 but it didn't go away when I tried vagrant destroy... still freezes)

setup
======
Win 7 pro
git bash
$ vagrant --version
Vagrant 2.2.2

$ vagrant up master
(or... retrying)
$ vagrant reload master --provision

Bringing machine 'master' up with 'virtualbox' provider...
==> master: Importing base box 'ol7-latest'...
==> master: Matching MAC address for NAT networking...
==> master: Setting the name of the VM: Kubernetes_master_1544738206907_88094
==> master: Couldn't find Cheffile at ./Cheffile.
==> master: Fixed port collision for 22 => 2222. Now on port 2202.
==> master: Vagrant has detected a configuration issue which exposes a
==> master: vulnerability with the installed version of VirtualBox. The
==> master: current guest is configured to use an E1000 NIC type for a
==> master: network adapter which is vulnerable in this version of VirtualBox.
==> master: Ensure the guest is trusted to use this configuration or update
==> master: the NIC type using one of the methods below:
==> master:
==> master:   https://www.vagrantup.com/docs/virtualbox/configuration.html#default-nic-type
==> master:   https://www.vagrantup.com/docs/virtualbox/networking.html#virtualbox-nic-type
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 8001 (guest) => 8001 (host) (adapter 1)
    master: 22 (guest) => 2202 (host) (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2202
    master: SSH username: vagrant
    master: SSH auth method: private key

**Comment by totalamateurhour** [comment]
As for the warnings about E1000 NIC, see https://github.com/hashicorp/vagrant/issues/10481

I noticed the following:

```
==> master: Couldn't find Cheffile at ./Cheffile.
```

Did you customize the Vagrantfile for master?

**Comment by erikhSSI** [comment]
Workaround
========
OK, so here is what worked for me.  I assumed the problem is that SSH wasn't working so...

1. After doing "$ virtual up master" the VirtualBox does show just fine in VB Manager.... so go to VBM and highlight the Kubernetes machine ... 
1.1 first you have to stop the machine
1.2 and go to Settings... Network... and remove "NETWORK ADAPTER 2" 
1.3 restart the machine

2. Then... back at command line:
$ vagrant ssh-config master 
to find the location of the key being used for SSH cert based login.  And test that I can now SSH in using the key (after turning it into a PPK with puttygen)

3. Now that SSH login is working:
$ vagrant provision master
 (because "vagrant up master" (or "vagrant reload master") just re-adds the problematic network adapter #2 we got rid of in step 1)

VOILA!
.
.
.
    master: Your Kubernetes VM is ready to use!
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running provisioner: shell...
    master: Running: inline script

**Comment by erikhSSI** [comment]
Hi Sergio, 
I appreciate the quick reply!

> As for the warnings about E1000 NIC, see [hashicorp/vagrant#10481](https://github.com/hashicorp/vagrant/issues/10481)

Yep, I need to upgrade my VBM.  But I sensed this wasn't the real issue.
 
> I noticed the following:
> 
> ```
> ==> master: Couldn't find Cheffile at ./Cheffile.
> ```
> Did you customize the Vagrantfile for master?

FWIW, I did nothing custom.  I just cloned the repo and "cd Kubernetes; vagrant up master"
