### ISSUE TITLE
Issue when starting 18.4.0-XE database

### ISSUE THREAD

**Issue by dbarj** [oracle/vagrant-boxes#91]
During 18.4.0-XE deployment, I got the error:

>     oracle18c-xe-vagrant: Installed:
>     oracle18c-xe-vagrant:   oracle-database-xe-18c.x86_64 0:1.0-1
>     oracle18c-xe-vagrant: Complete!
>     oracle18c-xe-vagrant: INSTALLER: Oracle software installed
>     oracle18c-xe-vagrant: Configuring Oracle Listener.
>     oracle18c-xe-vagrant: Listener configuration succeeded.
>     oracle18c-xe-vagrant: Configuring Oracle Database XE.
>     oracle18c-xe-vagrant: [FATAL] [DBT-06103] The port (5,500) is already in use.
>     oracle18c-xe-vagrant:    ACTION: Specify a free port.

If I try to run it manually, I get the same error:

> [root@sevenos ~]# /etc/init.d/oracle-xe-18c configure
> Configuring Oracle Listener.
> Listener configuration succeeded.
> Configuring Oracle Database XE.
> [FATAL] [DBT-06103] The port (5,500) is already in use.
>    ACTION: Specify a free port.
> 
> #This is a configuration file to setup the Oracle Database.
> Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.

I can see that port 5500 is not in use. The error is caused because the hostname was updated but not reflected on /etc/hostname:

> [root@sevenos ~]# cat /etc/hostname
> localhost.localdomain
> [root@sevenos ~]# cat /etc/hosts
> 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
> ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

After I change it manually, the configuration run smoothly:

> [root@sevenos ~]# hostnamectl set-hostname sevenos
> [root@sevenos ~]# cat /etc/hostname
> sevenos
> [root@sevenos ~]# /etc/init.d/oracle-xe-18c configure
> Configuring Oracle Listener.
> Listener configuration succeeded.
> Configuring Oracle Database XE.
> Enter SYS user password:
> 
> Enter SYSTEM user password:
> 
> Enter PDBADMIN User Password:
> 
> Prepare for db operation
> 7% complete
> ...

To solve the bug simply add command above on install script. Thanks.

**Comment by dbarj** [comment]
Hi @PaulNeumann ,

> $ VBoxManage -v
> 5.2.22r126460
> $ vagrant version
> Installed Version: 2.2.3
> Latest Version: 2.2.3
> 
> You're running an up-to-date version of Vagrant!

I solved this issue adding the following hostnamectl on install.sh, line 61:
```
chmod g+w /etc/sysconfig/oracle-xe-18c.conf && \
sed -i -e "s|###ORACLE_CHARACTERSET###|$ORACLE_CHARACTERSET|g" /etc/sysconfig/oracle-xe-18c.conf && \
sed -i -e "s|###ORACLE_PWD###|$ORACLE_PWD|g" /etc/sysconfig/oracle-xe-18c.conf
sudo hostnamectl set-hostname sevenos
su -l -c '/etc/init.d/oracle-xe-18c configure'
```

**Comment by PaulNeumann** [comment]
@dbarj, I'm glad that it's working for you now, but I'd like to try to figure out what happened. Setting the hostname shouldn't be necessary to get `oracle-xe-18c configure` to work correctly--localhost should work fine. I've used this box with VirtualBox 5.2.20 through 6.0.4 and Vagrant 2.2.0 through 2.2.3. See below:

![xe](https://user-images.githubusercontent.com/38871902/51992991-3d4bf700-246b-11e9-9d90-969bf5e38e2e.PNG)

In your initial post, it looks like the hostname was changed before you ran the configuration script. The "@sevenos" in `[root@sevenos ~]# /etc/init.d/oracle-xe-18c configure` indicates that the hostname had already been changed. Did you set the hostname before you ran `vagrant up` the first time, or after? How did you set it? I want to try to reproduce the issue, if I can.

Thanks,
Paul

**Comment by PaulNeumann** [comment]
@dbarj,

Thanks for clarifying. This helps a lot.

The "sevenos" hostname isn't being set by the 18.4.0-XE Vagrantfile or the ol7-latest base box that the 18.4.0-XE box is built on. This is why I asked when/how you set the hostname. I didn't think about the possibility that it was being defined somewhere else, but that seems to be what's happening.

So, if you have time, let's try to find out where the hostname is being defined. It might be set by another Vagrantfile that's being loaded before this project's Vagrantfile. Details on how Vagrantfiles are loaded/merged are in the [Vagrant docs](https://www.vagrantup.com/docs/vagrantfile/). A couple of things to check:

- Do you have the `VAGRANT_CWD` environment variable set? If so, is there a Vagrantfile in that directory? If there is, does it define a hostname?
- Is there a Vagrantfile in your Vagrant home directory (usually `~/.vagrant.d`)? If so, does it define a hostname?

Do either of these apply to your host?

Thanks,
Paul

**Comment by dbarj** [comment]
Hi @PaulNeumann , thanks for clarifying.

I executed the deployment once again today, after removing the "hostnamectl" and now it worked. So probably, as you said, my PC was merging some Vagrantfiles. I don't know how it was setting this "sevenos" hostname, probably from some old deployment that let a Vagrantfile behind.

Thanks for all the support. I will let you know if the issue returns.

**Comment by mfzaheer** [comment]
I am trying to install Oracle-18c-xe on Oracle Linux-7.8. 

Below errors are misleading
 "[FATAL] [DBT-06103] The port (5,500) is already in use.
   ACTION: Specify a free port.

or after changing the port to 5501

Configuring Oracle Database XE.
[FATAL] [DBT-06103] The port (5,501) is already in use.
   ACTION: Specify a free port.

My hostname in /etc/hosts and /etc/hostname were not the same. 
I have fixed the issue by syncing the hostname in /etc/hosts and /etc/hostname. 

There is no vagrant involved in my case. 

Regards,
Fayyaz
