### ISSUE TITLE
handle Oracle Linux yum server changes

### ISSUE THREAD

**Issue by gregrahn** [oracle/vagrant-boxes#92]
With the current version of `ol7-latest.box` (as of 31-Jan) and the [announced Oracle Linux yum server changes](https://blogs.oracle.com/linux/modularizing-the-oracle-linux-yum-server-repository-configurations-breaking-up-is-hard-to-do), the `install.sh` script fails.  One can see this in the output from `vagrant up`:

oracle-18c-vagrant: IMPORTANT: A legacy Oracle Linux yum server repo file was found. Oracle Linux yum server repository configurations have changed which means public-yum-ol7.repo will no longer be updated. New repository configuration files have been installed but are disabled. To complete the transition, run this script as the root user:
oracle-18c-vagrant:
oracle-18c-vagrant: /usr/bin/ol_yum_configure.sh

A quick fix is just to check for the existence of the yum repo script post update (insert the below [after line 20](https://github.com/oracle/vagrant-boxes/blob/master/OracleDatabase/18.3.0/scripts/install.sh#L20))

```
if [ -f /usr/bin/ol_yum_configure.sh ]; then
  echo 'INSTALLER: updating Oracle Linux yum server repo file'
  /usr/bin/ol_yum_configure.sh
  echo 'INSTALLER: updating Oracle Linux yum server repo file, done!'
fi
```
This allows the install to run to completion successfully.

**Comment by PaulNeumann** [comment]
@gregrahn,

When you say that the `install.sh` script fails, do you mean that the rest of the script doesn't run? When I build the 18c box (or any of the other Oracle Database boxes), I see the message about the yum repository transition, but it doesn't halt script execution. The database is successfully installed and configured, and the box works correctly.

If the script isn't running to completion, it would help if you could provide the output that appears after the yum repository transition message, along with the versions of VirtualBox and Vagrant that you're using.

If the script is running to completion, then one way to address the yum repository transition is to add a shell script in the `userscripts` directory before running `vagrant up` for the first time. The installer runs any shell and/or SQL scripts in the `userscripts` directory after the database is set up. For example, you could add a script called `complete_yum_transition.sh` in the `userscripts` directory with the following content:
```bash
#!/bin/bash
#

if [ -f /usr/bin/ol_yum_configure.sh ]; then
  su -l -c /usr/bin/ol_yum_configure.sh
fi
```
This would ensure that the yum repository configuration is correct until a new version of `ol7-latest.box` is released.

I hope this helps!

Paul

**Comment by gregrahn** [comment]
@PaulNeumann - the script runs to finish, but the Oracle install and beyond fails.  You can see the errors starting after the `oracle-18c-vagrant: INSTALLER: System updated` line.
https://gist.github.com/3d1481906947f764c957596d1d8f3aaa

**Comment by totalamateurhour** [comment]
@gregrahn Can you still ssh to this box? If so, what does the following show:

```
yum repolist
ls -l /etc/yum.repos.d
```

**Comment by PaulNeumann** [comment]
@gregrahn,

Thanks for providing the log. This helps.

I've built the Oracle Database boxes in this repository many times since the yum repository transition, using the latest version of `ol7-latest.box`, and I haven't seen the `There are no enabled repos.` message (lines 704 and 710 of the log) before. That's not how the process is "supposed" to work. Since there are no enabled repos, yum can't install the `oracle-database-preinstall-18c` rpm. Without the preinstall rpm, the rest of the installation and configuration fails.

I'll look at this some more and see what I can figure out.

Thanks,
Paul

**Comment by PaulNeumann** [comment]
@totalamateurhour In case it helps, I built this box after the original poster reported the issue, and it worked fine for me. I was wondering whether I hit a different CDN node and got different rpm versions, but that doesn't appear to be the case.
```
[vagrant@oracle-18c-vagrant ~]$ yum list installed oraclelinux-release-el7 yum-utils
Installed Packages
oraclelinux-release-el7.x86_64                         1.0-4.el7                                 @ol7_latest
yum-utils.noarch                                       1.1.31-50.0.1.el7
[vagrant@oracle-18c-vagrant ~]$ ls -l /etc/yum.repos.d
total 28
-rw-r--r--. 1 root root  3354 Jan 31 22:28 oracle-linux-ol7.repo.disabled
-rw-r--r--. 1 root root 14602 Nov 14 08:20 public-yum-ol7.repo
-rw-r--r--. 1 root root  2116 Jan 31 22:28 uek-ol7.repo.disabled
-rw-r--r--. 1 root root   226 Jan 25 15:35 virt-ol7.repo.disabled
```
I deliberately haven't run `ol_yum_configure.sh` yet.

**Comment by totalamateurhour** [comment]
@PaulNeumann Thanks - this is what I would expect. Like you, I'm puzzled by the `There are no enabled repos` message.

**Comment by gregrahn** [comment]
I'm not sure what has changed, but I destroyed my vm and started clean again, reverting my changes, and it succeeded this time.  Looking back at yesterday's log in the gist and comparing it to the successful one, this is [the thing](https://gist.github.com/gregrahn/3d1481906947f764c957596d1d8f3aaa#file-vagrant-boxes-db-18-0-3-log-L447-L448
) that stands out:
```
oracle-18c-vagrant: mv: cannot stat ‘/etc/yum.repos.d/public-yum-ol7.repo.20190201’: No such file or directory
    oracle-18c-vagrant: grep: /etc/yum.repos.d/public-yum-ol7.repo: No such file or directory
```
So not sure what caused that, but that seemed to set the course for the mishap with the repo.

My speculation would be something related to time zones in the script and the potential mismatch of the dated file name and the expected name, but not sure what may do that.

**Comment by PaulNeumann** [comment]
@gregrahn,

Excellent! I'm glad it's working for you now.

Unfortunately, I don't have an explanation for what went wrong the first time. I doubt that running the `ol_yum_configure.sh` script would have helped, because it doesn't do anything if `/etc/yum.repos.d/public-yum-ol7.repo` is missing (which apparently it was).

I don't know whether time zone was the problem. The date referenced in the log would have been in UTC, because the VM time zone isn't set to the host's time zone until a little later in the `install.sh` script. So, if you created the VM after 4:00 PM in your host's time zone yesterday, 20190201 would have been correct.

If I learn more, I'll let you know.

Thanks,
Paul

**Comment by totalamateurhour** [comment]
@gregrahn @PaulNeumann Oracle Linux 6.10 and 7.6 boxes on yum.oracle.com/boxes are updated. It could take a while to trickle through the CDN (akamai). These use the new modular yum repo approach.

**Comment by PaulNeumann** [comment]
@totalamateurhour Nice! Thanks for letting us know.

**Comment by gvenzl** [comment]
@totalamateurhour, I believe we can close this issue now that the boxes have been updated, correct?

**Comment by totalamateurhour** [comment]
Correct.
