### ISSUE TITLE
Newer Kubernetes deployment possible?

### ISSUE THREAD

**Issue by dluongiop** [oracle/vagrant-boxes#98]
I followed the guide to setup a Kubernetes cluster but noticed that Kubernetes 1.9 was deployed. I will try to update to 1.13 but is it possible to deploy version 1.13 from the start?

**Comment by AmedeeBulle** [comment]
You can only install Oracle builds, supported or _development preview_.
At this time we haven't released 1.13, so it it not possible yet to deploy (or upgrade to) 1.13.

But we have just released 1.12, so if you retry you should get a much newer release now:
```
[vagrant@master ~]$ kubectl get nodes
NAME                 STATUS     ROLES    AGE     VERSION
master.vagrant.vm    Ready      master   7m10s   v1.12.5+2.1.1.el7
worker1.vagrant.vm   Ready      <none>   3m34s   v1.12.5+2.1.1.el7
worker2.vagrant.vm   NotReady   <none>   26s     v1.12.5+2.1.1.el7
```

**Comment by dluongiop** [comment]
Thanks AmedeeBulle.
I retried and did get v1.12 deployed but I was expecting CoreDNS but it seems that KubeDNS is enabled instead. Is there a way I can deploy v1.12 with CoreDNS?

```
$ kubectl cluster-info
Kubernetes master is running at https://192.168.99.100:6443
KubeDNS is running at https://192.168.99.100:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

**Comment by AmedeeBulle** [comment]
`kube-dns` is the name of the service, not the container.

I do have CoreDNS on my vagrant setup:
```
[vagrant@master ~]$ kubectl get pod --namespace kube-system | grep dns
coredns-c9649d6fd-dcqh7                     1/1     Running   0          12h
coredns-c9649d6fd-h64jj                     1/1     Running   0          12h
```

**Comment by dluongiop** [comment]
Of course. Thank you.
