### ISSUE TITLE
Error in instructions for DB box post-setup scripts

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#99]
The recent enhancement to allow running user-defined post-setup scripts for the database boxes contained an error in the `README.md` and `put_custom_scripts_here.txt` files. The instructions in these files state that user-defined shell scripts will be executed as the vagrant user. This is incorrect. The `install.sh` script, and any shell scripts called from it, are executed as root. To demonstrate this, replace the `install.sh` script for any of the database boxes with the following, and run `vagrant up`.
```bash
#!/bin/bash
echo "INSTALLER: Script running as $(whoami)"
```
The last line of the output from Vagrant will be similar to:
```
oracle-12201-vagrant: INSTALLER: Script running as root
```
This issue is my fault. I thought I had verified how the scripts were run, but I was wrong, and I apologize. If you'd like, I can submit a PR to correct the instructions in these files.

**Comment by PaulNeumann** [comment]
I know you're very busy, so to hopefully save you some time, I've submitted a PR for this. I'm happy to make any changes that you'd like.

**Comment by gvenzl** [comment]
Thanks Paul!

**Comment by gvenzl** [comment]
Merged.
